project:
  type: website
  output-dir: docs

website:
  title: "EIP Data Website"
  navbar:
    right:
      - href: main.qmd
        text: Home
      - text: Clinical
        menu:
          - href: hcv.qmd
            text: HCV
          - href: sud.qmd
            text: SUD
          - href: human_trafficking.qmd
            text: Human Trafficking
      - text: Deliverables
        menu:
          - href: ctr_deliverables.qmd
            text: CTR Deliverables
          - href: ehe_deliverables.qmd
            text: EHE Deliverables
          - href: naccho2.qmd
            text: NACCHO-2 Deliverables
      - text: Research
        menu:
          - href: pgx.qmd
            text: PGx
      - text: Sites
        menu:
          - href: ucmc.qmd
            text: UCMC
          - href: wch.qmd
            text: WCH
          - href: exchange.qmd
            text: Exchange
          - href: talbert.qmd
            text: Talbert
          - href: community.qmd
            text: Other Community Sites

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



