---
title: "Mental Health"
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r Data, include=FALSE}

rm(list=ls(all=T))

library(dplyr)
library(tidyverse)
library(lubridate)
library(plotly)
library(ggplot2)
library(reactable)
library(htmltools)
library(lubridate)
library(hrbrthemes)
library(gt)
library(janitor)
library(scales)
library(apyramid)
library(kableExtra)
library(knitr)
library(zoo)

### EIP Database Data
# 2023
eip23 <- read.csv('M:/EIP Data/EIP Database/REDCap 2023/EIP Database Data 20240723_0942.csv')
dim(eip23)
summary(eip23$record_id)
eip23$record_id <- paste(eip23$record_id, "_23", sep = "")
summary(eip23$record_id)

# 2024
eip24 <- read.csv('M:/EIP Data/EIP Database/REDCap 2024/EIP Database Data 20240802_1419.csv')
dim(eip24)
summary(eip24$record_id)
eip24$record_id <- paste(eip24$record_id, "_24", sep = "")
summary(eip24$record_id)

```

```{r Patient Data to Encounter, include=FALSE}

### Person-level data is only visit_001_arm_1, use to match to encounters

# 2023
table(eip23$redcap_event_name)
person <- eip23[which(eip23$redcap_event_name == 'visit_001_arm_1'), ]
dim(person)

person <- select(person, record_id, mrn, dob, 
                 race___1, race___2, race___3, race___4, race___5, race___6, ethnicity,
                 sex_raised, sex_selfdefined, insurance, address_county,
                 address_zip_code,
                 followup_date1, followup_date2, followup_date3, followup_date4,
                 followup_date5, followup_date6, followup_date7, followup_date8,
                 followup_date9, followup_date10, followup_date11, followup_date12,
                 followup_date13, followup_date14, followup_date15, followup_date16,
                 followup_date17, followup_date18, followup_date19, followup_date20,
                 followup_date21, followup_date22, followup_date23, followup_date24,
                 followup_date25, followup_date26, followup_date27, followup_date28,
                 followup_date29, followup_date30, followup_date31, followup_date32,
                 followup_date33, followup_date34, followup_date35, followup_date36,
                 followup_date37, followup_date38, followup_date39, followup_date40,
                 followup_date41, followup_date42, followup_date43, followup_date44,
                 followup_date45, followup_date46, followup_date47, followup_date48,
                 followup_date49, followup_date50, followup_counselor1, followup_counselor2,
                 followup_counselor3, followup_counselor4, followup_counselor5,
                 followup_counselor6, followup_counselor7, followup_counselor8,
                 followup_counselor9, followup_counselor10, followup_counselor11,
                 followup_counselor12, followup_counselor13, followup_counselor14,
                 followup_counselor15, followup_counselor16, followup_counselor17,
                 followup_counselor18, followup_counselor19, followup_counselor20,
                 followup_counselor21, followup_counselor22, followup_counselor23,
                 followup_counselor24, followup_counselor25, followup_counselor26,
                 followup_counselor27, followup_counselor28, followup_counselor29,
                 followup_counselor30, followup_counselor31, followup_counselor32,
                 followup_counselor33, followup_counselor34, followup_counselor35,
                 followup_counselor36, followup_counselor37, followup_counselor38,
                 followup_counselor39, followup_counselor40, followup_counselor41,
                 followup_counselor42, followup_counselor43, followup_counselor44,
                 followup_counselor45, followup_counselor46, followup_counselor47,
                 followup_counselor48, followup_counselor49, followup_counselor50,
                 ltc_service1___8, ltc_service2___8,
                 ltc_service3___8, ltc_service4___8, ltc_service5___8,
                 ltc_service6___8, ltc_service7___8, ltc_service8___8,
                 ltc_service9___8, ltc_service10___8, ltc_service11___8,
                 ltc_service12___8, ltc_service13___8, ltc_service14___8,
                 ltc_service15___8, ltc_service16___8, ltc_service17___8,
                 ltc_service18___8, ltc_service19___8, ltc_service20___8,
                 ltc_service21___8, ltc_service22___8, ltc_service23___8,
                 ltc_service24___8, ltc_service25___8, ltc_service26___8,
                 ltc_service27___8, ltc_service28___8, ltc_service29___8,
                 ltc_service30___8, ltc_service31___8, ltc_service32___8,
                 ltc_service33___8, ltc_service34___8, ltc_service35___8,
                 ltc_service36___8, ltc_service37___8, ltc_service38___8,
                 ltc_service39___8, ltc_service40___8, ltc_service41___8,
                 ltc_service42___8, ltc_service43___8, ltc_service44___8,
                 ltc_service45___8, ltc_service46___8, ltc_service47___8,
                 ltc_service48___8, ltc_service49___8, ltc_service50___8,
                 naccho_contact_day1, naccho_contact_day2,
                 naccho_contact_day3, naccho_contact_day4, naccho_contact_day5,
                 naccho_contact_day6, naccho_contact_day7, naccho_contact_day8,
                 naccho_contact_day9, naccho_contact_day10, naccho_contact_day11,
                 naccho_contact_day12, naccho_contact_day13, naccho_contact_day14,
                 naccho_contact_day15, naccho_contact_day16, naccho_contact_day17,
                 naccho_contact_day18, naccho_contact_day19, naccho_contact_day20,
                 naccho_contact_day21, naccho_contact_day22, naccho_contact_day23,
                 naccho_contact_day24, naccho_contact_day25, naccho_contact_day26,
                 naccho_contact_day27, naccho_contact_day28, naccho_contact_day29,
                 naccho_contact_day30, naccho_contact_day31, naccho_contact_day32,
                 naccho_contact_day33, naccho_contact_day34, naccho_contact_day35,
                 naccho_contact_day36, naccho_contact_day37, naccho_contact_day38,
                 naccho_contact_day39, naccho_contact_day40, naccho_contact_day41,
                 naccho_contact_day42, naccho_contact_day43, naccho_contact_day44,
                 naccho_contact_day45, naccho_contact_day46, naccho_contact_day47,
                 naccho_contact_day48, naccho_contact_day49, naccho_contact_day50,
                 naccho_contact_confirm_tx1, naccho_contact_confirm_tx2,
                 naccho_contact_confirm_tx3, naccho_contact_confirm_tx4, naccho_contact_confirm_tx5,
                 naccho_contact_confirm_tx6, naccho_contact_confirm_tx7, naccho_contact_confirm_tx8,
                 naccho_contact_confirm_tx9, naccho_contact_confirm_tx10, naccho_contact_confirm_tx11,
                 naccho_contact_confirm_tx12, naccho_contact_confirm_tx13, naccho_contact_confirm_tx14,
                 naccho_contact_confirm_tx15, naccho_contact_confirm_tx16, naccho_contact_confirm_tx17,
                 naccho_contact_confirm_tx18, naccho_contact_confirm_tx19, naccho_contact_confirm_tx20,
                 naccho_contact_confirm_tx21, naccho_contact_confirm_tx22, naccho_contact_confirm_tx23,
                 naccho_contact_confirm_tx24, naccho_contact_confirm_tx25, naccho_contact_confirm_tx26,
                 naccho_contact_confirm_tx27, naccho_contact_confirm_tx28, naccho_contact_confirm_tx29,
                 naccho_contact_confirm_tx30, naccho_contact_confirm_tx31, naccho_contact_confirm_tx32,
                 naccho_contact_confirm_tx33, naccho_contact_confirm_tx34, naccho_contact_confirm_tx35,
                 naccho_contact_confirm_tx36, naccho_contact_confirm_tx37, naccho_contact_confirm_tx38,
                 naccho_contact_confirm_tx39, naccho_contact_confirm_tx40, naccho_contact_confirm_tx41,
                 naccho_contact_confirm_tx42, naccho_contact_confirm_tx43, naccho_contact_confirm_tx44,
                 naccho_contact_confirm_tx45, naccho_contact_confirm_tx46, naccho_contact_confirm_tx47,
                 naccho_contact_confirm_tx48, naccho_contact_confirm_tx49, naccho_contact_confirm_tx50,
                 who_initiated_contact1, who_initiated_contact2, who_initiated_contact3, who_initiated_contact4, who_initiated_contact5,
                 who_initiated_contact6, who_initiated_contact7, who_initiated_contact8, who_initiated_contact9, who_initiated_contact10,
                 who_initiated_contact11, who_initiated_contact12, who_initiated_contact13, who_initiated_contact14,
                 who_initiated_contact15, who_initiated_contact16, who_initiated_contact17, who_initiated_contact18,
                 who_initiated_contact19, who_initiated_contact20, who_initiated_contact21, who_initiated_contact22,
                 who_initiated_contact23, who_initiated_contact24, who_initiated_contact25, who_initiated_contact26,
                 who_initiated_contact27, who_initiated_contact28, who_initiated_contact29, who_initiated_contact30,
                 who_initiated_contact31, who_initiated_contact32, who_initiated_contact33, who_initiated_contact34,
                 who_initiated_contact35, who_initiated_contact36, who_initiated_contact37, who_initiated_contact38,
                 who_initiated_contact39, who_initiated_contact40, who_initiated_contact41, who_initiated_contact42,
                 who_initiated_contact43, who_initiated_contact44, who_initiated_contact45, who_initiated_contact46,
                 who_initiated_contact47, who_initiated_contact48, who_initiated_contact49, who_initiated_contact50,
                 contact_with1, contact_with2, contact_with3, contact_with4, contact_with5,
                 contact_with6, contact_with7, contact_with8, contact_with9, contact_with10,
                 contact_with11, contact_with12, contact_with13, contact_with14,
                 contact_with15, contact_with16, contact_with17, contact_with18,
                 contact_with19, contact_with20, contact_with21, contact_with22,
                 contact_with23, contact_with24, contact_with25, contact_with26,
                 contact_with27, contact_with28, contact_with29, contact_with30,
                 contact_with31, contact_with32, contact_with33, contact_with34,
                 contact_with35, contact_with36, contact_with37, contact_with38,
                 contact_with39, contact_with40, contact_with41, contact_with42,
                 contact_with43, contact_with44, contact_with45, contact_with46,
                 contact_with47, contact_with48, contact_with49, contact_with50,
                 ltc_contact1, ltc_contact2, ltc_contact3, ltc_contact4, ltc_contact5,
                 ltc_contact6, ltc_contact7, ltc_contact8, ltc_contact9, ltc_contact10,
                 ltc_contact11, ltc_contact12, ltc_contact13, ltc_contact14, ltc_contact15,
                 ltc_contact16, ltc_contact17, ltc_contact18, ltc_contact19, ltc_contact20,
                 ltc_contact21, ltc_contact22, ltc_contact23, ltc_contact24, ltc_contact25,
                 ltc_contact26, ltc_contact27, ltc_contact28, ltc_contact29, ltc_contact30,
                 ltc_contact31, ltc_contact32, ltc_contact33, ltc_contact34, ltc_contact35,
                 ltc_contact36, ltc_contact37, ltc_contact38, ltc_contact39, ltc_contact40,
                 ltc_contact41, ltc_contact42, ltc_contact43, ltc_contact44, ltc_contact45,
                 ltc_contact46, ltc_contact47, ltc_contact48, ltc_contact49, ltc_contact50,
                 no_contact_reason1, no_contact_reason2, no_contact_reason3, no_contact_reason4, no_contact_reason5,
                 no_contact_reason6, no_contact_reason7, no_contact_reason8, no_contact_reason9, no_contact_reason10,
                 no_contact_reason11, no_contact_reason12, no_contact_reason13, no_contact_reason14,
                 no_contact_reason15, no_contact_reason16, no_contact_reason17, no_contact_reason18,
                 no_contact_reason19, no_contact_reason20, no_contact_reason21, no_contact_reason22,
                 no_contact_reason23, no_contact_reason24, no_contact_reason25, no_contact_reason26,
                 no_contact_reason27, no_contact_reason28, no_contact_reason29, no_contact_reason30,
                 no_contact_reason31, no_contact_reason32, no_contact_reason33, no_contact_reason34,
                 no_contact_reason35, no_contact_reason36, no_contact_reason37, no_contact_reason38,
                 no_contact_reason39, no_contact_reason40, no_contact_reason41, no_contact_reason42,
                 no_contact_reason43, no_contact_reason44, no_contact_reason45, no_contact_reason46,
                 no_contact_reason47, no_contact_reason48, no_contact_reason49, no_contact_reason50)
dim(person)

eip23 <- select(eip23, -mrn, -dob, 
               -race___1, -race___2, -race___3, -race___4, -race___5, 
               -race___6, -ethnicity,
               -sex_raised, -sex_selfdefined, -insurance, -address_county,
               -address_zip_code,
               -followup_date1, -followup_date2, -followup_date3, -followup_date4,
               -followup_date5, -followup_date6, -followup_date7, -followup_date8,
               -followup_date9, -followup_date10, -followup_date11, -followup_date12,
               -followup_date13, -followup_date14, -followup_date15, -followup_date16,
               -followup_date17, -followup_date18, -followup_date19, -followup_date20,
               -followup_date21, -followup_date22, -followup_date23, -followup_date24,
               -followup_date25, -followup_date26, -followup_date27, -followup_date28,
               -followup_date29, -followup_date30, -followup_date31, -followup_date32,
               -followup_date33, -followup_date34, -followup_date35, -followup_date36,
               -followup_date37, -followup_date38, -followup_date39, -followup_date40,
               -followup_date41, -followup_date42, -followup_date43, -followup_date44,
               -followup_date45, -followup_date46, -followup_date47, -followup_date48,
               -followup_date49, -followup_date50, -followup_counselor1, -followup_counselor2,
               -followup_counselor3, -followup_counselor4, -followup_counselor5,
               -followup_counselor6, -followup_counselor7, -followup_counselor8,
               -followup_counselor9, -followup_counselor10, -followup_counselor11,
               -followup_counselor12, -followup_counselor13, -followup_counselor14,
               -followup_counselor15, -followup_counselor16, -followup_counselor17,
               -followup_counselor18, -followup_counselor19, -followup_counselor20,
               -followup_counselor21, -followup_counselor22, -followup_counselor23,
               -followup_counselor24, -followup_counselor25, -followup_counselor26,
               -followup_counselor27, -followup_counselor28, -followup_counselor29,
               -followup_counselor30, -followup_counselor31, -followup_counselor32,
               -followup_counselor33, -followup_counselor34, -followup_counselor35,
               -followup_counselor36, -followup_counselor37, -followup_counselor38,
               -followup_counselor39, -followup_counselor40, -followup_counselor41,
               -followup_counselor42, -followup_counselor43, -followup_counselor44,
               -followup_counselor45, -followup_counselor46, -followup_counselor47,
               -followup_counselor48, -followup_counselor49, -followup_counselor50,
               -ltc_service1___8, -ltc_service2___8,
               -ltc_service3___8, -ltc_service4___8, -ltc_service5___8,
               -ltc_service6___8, -ltc_service7___8, -ltc_service8___8,
               -ltc_service9___8, -ltc_service10___8, -ltc_service11___8,
               -ltc_service12___8, -ltc_service13___8, -ltc_service14___8,
               -ltc_service15___8, -ltc_service16___8, -ltc_service17___8,
               -ltc_service18___8, -ltc_service19___8, -ltc_service20___8,
               -ltc_service21___8, -ltc_service22___8, -ltc_service23___8,
               -ltc_service24___8, -ltc_service25___8, -ltc_service26___8,
               -ltc_service27___8, -ltc_service28___8, -ltc_service29___8,
               -ltc_service30___8, -ltc_service31___8, -ltc_service32___8,
               -ltc_service33___8, -ltc_service34___8, -ltc_service35___8,
               -ltc_service36___8, -ltc_service37___8, -ltc_service38___8,
               -ltc_service39___8, -ltc_service40___8, -ltc_service41___8,
               -ltc_service42___8, -ltc_service43___8, -ltc_service44___8,
               -ltc_service45___8, -ltc_service46___8, -ltc_service47___8,
               -ltc_service48___8, -ltc_service49___8, -ltc_service50___8,
               -naccho_contact_day1, -naccho_contact_day2,
               -naccho_contact_day3, -naccho_contact_day4, -naccho_contact_day5,
               -naccho_contact_day6, -naccho_contact_day7, -naccho_contact_day8,
               -naccho_contact_day9, -naccho_contact_day10, -naccho_contact_day11,
               -naccho_contact_day12, -naccho_contact_day13, -naccho_contact_day14,
               -naccho_contact_day15, -naccho_contact_day16, -naccho_contact_day17,
               -naccho_contact_day18, -naccho_contact_day19, -naccho_contact_day20,
               -naccho_contact_day21, -naccho_contact_day22, -naccho_contact_day23,
               -naccho_contact_day24, -naccho_contact_day25, -naccho_contact_day26,
               -naccho_contact_day27, -naccho_contact_day28, -naccho_contact_day29,
               -naccho_contact_day30, -naccho_contact_day31, -naccho_contact_day32,
               -naccho_contact_day33, -naccho_contact_day34, -naccho_contact_day35,
               -naccho_contact_day36, -naccho_contact_day37, -naccho_contact_day38,
               -naccho_contact_day39, -naccho_contact_day40, -naccho_contact_day41,
               -naccho_contact_day42, -naccho_contact_day43, -naccho_contact_day44,
               -naccho_contact_day45, -naccho_contact_day46, -naccho_contact_day47,
               -naccho_contact_day48, -naccho_contact_day49, -naccho_contact_day50,
               -naccho_contact_confirm_tx1, -naccho_contact_confirm_tx2,
               -naccho_contact_confirm_tx3, -naccho_contact_confirm_tx4, -naccho_contact_confirm_tx5,
               -naccho_contact_confirm_tx6, -naccho_contact_confirm_tx7, -naccho_contact_confirm_tx8,
               -naccho_contact_confirm_tx9, -naccho_contact_confirm_tx10, -naccho_contact_confirm_tx11,
               -naccho_contact_confirm_tx12, -naccho_contact_confirm_tx13, -naccho_contact_confirm_tx14,
               -naccho_contact_confirm_tx15, -naccho_contact_confirm_tx16, -naccho_contact_confirm_tx17,
               -naccho_contact_confirm_tx18, -naccho_contact_confirm_tx19, -naccho_contact_confirm_tx20,
               -naccho_contact_confirm_tx21, -naccho_contact_confirm_tx22, -naccho_contact_confirm_tx23,
               -naccho_contact_confirm_tx24, -naccho_contact_confirm_tx25, -naccho_contact_confirm_tx26,
               -naccho_contact_confirm_tx27, -naccho_contact_confirm_tx28, -naccho_contact_confirm_tx29,
               -naccho_contact_confirm_tx30, -naccho_contact_confirm_tx31, -naccho_contact_confirm_tx32,
               -naccho_contact_confirm_tx33, -naccho_contact_confirm_tx34, -naccho_contact_confirm_tx35,
               -naccho_contact_confirm_tx36, -naccho_contact_confirm_tx37, -naccho_contact_confirm_tx38,
               -naccho_contact_confirm_tx39, -naccho_contact_confirm_tx40, -naccho_contact_confirm_tx41,
               -naccho_contact_confirm_tx42, -naccho_contact_confirm_tx43, -naccho_contact_confirm_tx44,
               -naccho_contact_confirm_tx45, -naccho_contact_confirm_tx46, -naccho_contact_confirm_tx47,
               -naccho_contact_confirm_tx48, -naccho_contact_confirm_tx49, -naccho_contact_confirm_tx50,
               -who_initiated_contact1, -who_initiated_contact2, -who_initiated_contact3, -who_initiated_contact4, -who_initiated_contact5,
               -who_initiated_contact6, -who_initiated_contact7, -who_initiated_contact8, -who_initiated_contact9, -who_initiated_contact10,
               -who_initiated_contact11, -who_initiated_contact12, -who_initiated_contact13, -who_initiated_contact14,
               -who_initiated_contact15, -who_initiated_contact16, -who_initiated_contact17, -who_initiated_contact18,
               -who_initiated_contact19, -who_initiated_contact20, -who_initiated_contact21, -who_initiated_contact22,
               -who_initiated_contact23, -who_initiated_contact24, -who_initiated_contact25, -who_initiated_contact26,
               -who_initiated_contact27, -who_initiated_contact28, -who_initiated_contact29, -who_initiated_contact30,
               -who_initiated_contact31, -who_initiated_contact32, -who_initiated_contact33, -who_initiated_contact34,
               -who_initiated_contact35, -who_initiated_contact36, -who_initiated_contact37, -who_initiated_contact38,
               -who_initiated_contact39, -who_initiated_contact40, -who_initiated_contact41, -who_initiated_contact42,
               -who_initiated_contact43, -who_initiated_contact44, -who_initiated_contact45, -who_initiated_contact46,
               -who_initiated_contact47, -who_initiated_contact48, -who_initiated_contact49, -who_initiated_contact50,
               -contact_with1, -contact_with2, -contact_with3, -contact_with4, -contact_with5,
               -contact_with6, -contact_with7, -contact_with8, -contact_with9, -contact_with10,
               -contact_with11, -contact_with12, -contact_with13, -contact_with14,
               -contact_with15, -contact_with16, -contact_with17, -contact_with18,
               -contact_with19, -contact_with20, -contact_with21, -contact_with22,
               -contact_with23, -contact_with24, -contact_with25, -contact_with26,
               -contact_with27, -contact_with28, -contact_with29, -contact_with30,
               -contact_with31, -contact_with32, -contact_with33, -contact_with34,
               -contact_with35, -contact_with36, -contact_with37, -contact_with38,
               -contact_with39, -contact_with40, -contact_with41, -contact_with42,
               -contact_with43, -contact_with44, -contact_with45, -contact_with46,
               -contact_with47, -contact_with48, -contact_with49, -contact_with50,
               -ltc_contact1, -ltc_contact2, -ltc_contact3, -ltc_contact4, -ltc_contact5,
               -ltc_contact6, -ltc_contact7, -ltc_contact8, -ltc_contact9, -ltc_contact10,
               -ltc_contact11, -ltc_contact12, -ltc_contact13, -ltc_contact14, -ltc_contact15,
               -ltc_contact16, -ltc_contact17, -ltc_contact18, -ltc_contact19, -ltc_contact20,
               -ltc_contact21, -ltc_contact22, -ltc_contact23, -ltc_contact24, -ltc_contact25,
               -ltc_contact26, -ltc_contact27, -ltc_contact28, -ltc_contact29, -ltc_contact30,
               -ltc_contact31, -ltc_contact32, -ltc_contact33, -ltc_contact34, -ltc_contact35,
               -ltc_contact36, -ltc_contact37, -ltc_contact38, -ltc_contact39, -ltc_contact40,
               -ltc_contact41, -ltc_contact42, -ltc_contact43, -ltc_contact44, -ltc_contact45,
               -ltc_contact46, -ltc_contact47, -ltc_contact48, -ltc_contact49, -ltc_contact50,
               -no_contact_reason1, -no_contact_reason2, -no_contact_reason3, -no_contact_reason4, -no_contact_reason5,
               -no_contact_reason6, -no_contact_reason7, -no_contact_reason8, -no_contact_reason9, -no_contact_reason10,
               -no_contact_reason11, -no_contact_reason12, -no_contact_reason13, -no_contact_reason14,
               -no_contact_reason15, -no_contact_reason16, -no_contact_reason17, -no_contact_reason18,
               -no_contact_reason19, -no_contact_reason20, -no_contact_reason21, -no_contact_reason22,
               -no_contact_reason23, -no_contact_reason24, -no_contact_reason25, -no_contact_reason26,
               -no_contact_reason27, -no_contact_reason28, -no_contact_reason29, -no_contact_reason30,
               -no_contact_reason31, -no_contact_reason32, -no_contact_reason33, -no_contact_reason34,
               -no_contact_reason35, -no_contact_reason36, -no_contact_reason37, -no_contact_reason38,
               -no_contact_reason39, -no_contact_reason40, -no_contact_reason41, -no_contact_reason42,
               -no_contact_reason43, -no_contact_reason44, -no_contact_reason45, -no_contact_reason46,
               -no_contact_reason47, -no_contact_reason48, -no_contact_reason49, -no_contact_reason50)

# Merge person dataset with full eip dataset

dim(eip23)
dim(person)
eip23 <- merge(eip23, person, by='record_id', all.x=T)
dim(eip23)
eip23 <- distinct(eip23)
dim(eip23)


# 2024
table(eip24$redcap_event_name)
person <- eip24[which(eip24$redcap_event_name == 'visit_001_arm_1'), ]
dim(person)

person <- select(person, record_id, mrn, dob, 
                 race___1, race___2, race___3, race___4, race___5, race___6, ethnicity,
                 sex_raised, sex_selfdefined, insurance, address_county,
                 address_zip_code,
                 followup_date1, followup_date2, followup_date3, followup_date4,
                 followup_date5, followup_date6, followup_date7, followup_date8,
                 followup_date9, followup_date10, followup_date11, followup_date12,
                 followup_date13, followup_date14, followup_date15, followup_date16,
                 followup_date17, followup_date18, followup_date19, followup_date20,
                 followup_date21, followup_date22, followup_date23, followup_date24,
                 followup_date25, followup_date26, followup_date27, followup_date28,
                 followup_date29, followup_date30, followup_date31, followup_date32,
                 followup_date33, followup_date34, followup_date35, followup_date36,
                 followup_date37, followup_date38, followup_date39, followup_date40,
                 followup_date41, followup_date42, followup_date43, followup_date44,
                 followup_date45, followup_date46, followup_date47, followup_date48,
                 followup_date49, followup_date50, followup_counselor1, followup_counselor2,
                 followup_counselor3, followup_counselor4, followup_counselor5,
                 followup_counselor6, followup_counselor7, followup_counselor8,
                 followup_counselor9, followup_counselor10, followup_counselor11,
                 followup_counselor12, followup_counselor13, followup_counselor14,
                 followup_counselor15, followup_counselor16, followup_counselor17,
                 followup_counselor18, followup_counselor19, followup_counselor20,
                 followup_counselor21, followup_counselor22, followup_counselor23,
                 followup_counselor24, followup_counselor25, followup_counselor26,
                 followup_counselor27, followup_counselor28, followup_counselor29,
                 followup_counselor30, followup_counselor31, followup_counselor32,
                 followup_counselor33, followup_counselor34, followup_counselor35,
                 followup_counselor36, followup_counselor37, followup_counselor38,
                 followup_counselor39, followup_counselor40, followup_counselor41,
                 followup_counselor42, followup_counselor43, followup_counselor44,
                 followup_counselor45, followup_counselor46, followup_counselor47,
                 followup_counselor48, followup_counselor49, followup_counselor50,
                 ltc_service1___8, ltc_service2___8,
                 ltc_service3___8, ltc_service4___8, ltc_service5___8,
                 ltc_service6___8, ltc_service7___8, ltc_service8___8,
                 ltc_service9___8, ltc_service10___8, ltc_service11___8,
                 ltc_service12___8, ltc_service13___8, ltc_service14___8,
                 ltc_service15___8, ltc_service16___8, ltc_service17___8,
                 ltc_service18___8, ltc_service19___8, ltc_service20___8,
                 ltc_service21___8, ltc_service22___8, ltc_service23___8,
                 ltc_service24___8, ltc_service25___8, ltc_service26___8,
                 ltc_service27___8, ltc_service28___8, ltc_service29___8,
                 ltc_service30___8, ltc_service31___8, ltc_service32___8,
                 ltc_service33___8, ltc_service34___8, ltc_service35___8,
                 ltc_service36___8, ltc_service37___8, ltc_service38___8,
                 ltc_service39___8, ltc_service40___8, ltc_service41___8,
                 ltc_service42___8, ltc_service43___8, ltc_service44___8,
                 ltc_service45___8, ltc_service46___8, ltc_service47___8,
                 ltc_service48___8, ltc_service49___8, ltc_service50___8,
                 naccho_contact_day1, naccho_contact_day2,
                 naccho_contact_day3, naccho_contact_day4, naccho_contact_day5,
                 naccho_contact_day6, naccho_contact_day7, naccho_contact_day8,
                 naccho_contact_day9, naccho_contact_day10, naccho_contact_day11,
                 naccho_contact_day12, naccho_contact_day13, naccho_contact_day14,
                 naccho_contact_day15, naccho_contact_day16, naccho_contact_day17,
                 naccho_contact_day18, naccho_contact_day19, naccho_contact_day20,
                 naccho_contact_day21, naccho_contact_day22, naccho_contact_day23,
                 naccho_contact_day24, naccho_contact_day25, naccho_contact_day26,
                 naccho_contact_day27, naccho_contact_day28, naccho_contact_day29,
                 naccho_contact_day30, naccho_contact_day31, naccho_contact_day32,
                 naccho_contact_day33, naccho_contact_day34, naccho_contact_day35,
                 naccho_contact_day36, naccho_contact_day37, naccho_contact_day38,
                 naccho_contact_day39, naccho_contact_day40, naccho_contact_day41,
                 naccho_contact_day42, naccho_contact_day43, naccho_contact_day44,
                 naccho_contact_day45, naccho_contact_day46, naccho_contact_day47,
                 naccho_contact_day48, naccho_contact_day49, naccho_contact_day50,
                 naccho_contact_confirm_tx1, naccho_contact_confirm_tx2,
                 naccho_contact_confirm_tx3, naccho_contact_confirm_tx4, naccho_contact_confirm_tx5,
                 naccho_contact_confirm_tx6, naccho_contact_confirm_tx7, naccho_contact_confirm_tx8,
                 naccho_contact_confirm_tx9, naccho_contact_confirm_tx10, naccho_contact_confirm_tx11,
                 naccho_contact_confirm_tx12, naccho_contact_confirm_tx13, naccho_contact_confirm_tx14,
                 naccho_contact_confirm_tx15, naccho_contact_confirm_tx16, naccho_contact_confirm_tx17,
                 naccho_contact_confirm_tx18, naccho_contact_confirm_tx19, naccho_contact_confirm_tx20,
                 naccho_contact_confirm_tx21, naccho_contact_confirm_tx22, naccho_contact_confirm_tx23,
                 naccho_contact_confirm_tx24, naccho_contact_confirm_tx25, naccho_contact_confirm_tx26,
                 naccho_contact_confirm_tx27, naccho_contact_confirm_tx28, naccho_contact_confirm_tx29,
                 naccho_contact_confirm_tx30, naccho_contact_confirm_tx31, naccho_contact_confirm_tx32,
                 naccho_contact_confirm_tx33, naccho_contact_confirm_tx34, naccho_contact_confirm_tx35,
                 naccho_contact_confirm_tx36, naccho_contact_confirm_tx37, naccho_contact_confirm_tx38,
                 naccho_contact_confirm_tx39, naccho_contact_confirm_tx40, naccho_contact_confirm_tx41,
                 naccho_contact_confirm_tx42, naccho_contact_confirm_tx43, naccho_contact_confirm_tx44,
                 naccho_contact_confirm_tx45, naccho_contact_confirm_tx46, naccho_contact_confirm_tx47,
                 naccho_contact_confirm_tx48, naccho_contact_confirm_tx49, naccho_contact_confirm_tx50,
                 who_initiated_contact1, who_initiated_contact2, who_initiated_contact3, who_initiated_contact4, who_initiated_contact5,
                 who_initiated_contact6, who_initiated_contact7, who_initiated_contact8, who_initiated_contact9, who_initiated_contact10,
                 who_initiated_contact11, who_initiated_contact12, who_initiated_contact13, who_initiated_contact14,
                 who_initiated_contact15, who_initiated_contact16, who_initiated_contact17, who_initiated_contact18,
                 who_initiated_contact19, who_initiated_contact20, who_initiated_contact21, who_initiated_contact22,
                 who_initiated_contact23, who_initiated_contact24, who_initiated_contact25, who_initiated_contact26,
                 who_initiated_contact27, who_initiated_contact28, who_initiated_contact29, who_initiated_contact30,
                 who_initiated_contact31, who_initiated_contact32, who_initiated_contact33, who_initiated_contact34,
                 who_initiated_contact35, who_initiated_contact36, who_initiated_contact37, who_initiated_contact38,
                 who_initiated_contact39, who_initiated_contact40, who_initiated_contact41, who_initiated_contact42,
                 who_initiated_contact43, who_initiated_contact44, who_initiated_contact45, who_initiated_contact46,
                 who_initiated_contact47, who_initiated_contact48, who_initiated_contact49, who_initiated_contact50,
                 contact_with1, contact_with2, contact_with3, contact_with4, contact_with5,
                 contact_with6, contact_with7, contact_with8, contact_with9, contact_with10,
                 contact_with11, contact_with12, contact_with13, contact_with14,
                 contact_with15, contact_with16, contact_with17, contact_with18,
                 contact_with19, contact_with20, contact_with21, contact_with22,
                 contact_with23, contact_with24, contact_with25, contact_with26,
                 contact_with27, contact_with28, contact_with29, contact_with30,
                 contact_with31, contact_with32, contact_with33, contact_with34,
                 contact_with35, contact_with36, contact_with37, contact_with38,
                 contact_with39, contact_with40, contact_with41, contact_with42,
                 contact_with43, contact_with44, contact_with45, contact_with46,
                 contact_with47, contact_with48, contact_with49, contact_with50,
                 ltc_contact1, ltc_contact2, ltc_contact3, ltc_contact4, ltc_contact5,
                 ltc_contact6, ltc_contact7, ltc_contact8, ltc_contact9, ltc_contact10,
                 ltc_contact11, ltc_contact12, ltc_contact13, ltc_contact14, ltc_contact15,
                 ltc_contact16, ltc_contact17, ltc_contact18, ltc_contact19, ltc_contact20,
                 ltc_contact21, ltc_contact22, ltc_contact23, ltc_contact24, ltc_contact25,
                 ltc_contact26, ltc_contact27, ltc_contact28, ltc_contact29, ltc_contact30,
                 ltc_contact31, ltc_contact32, ltc_contact33, ltc_contact34, ltc_contact35,
                 ltc_contact36, ltc_contact37, ltc_contact38, ltc_contact39, ltc_contact40,
                 ltc_contact41, ltc_contact42, ltc_contact43, ltc_contact44, ltc_contact45,
                 ltc_contact46, ltc_contact47, ltc_contact48, ltc_contact49, ltc_contact50,
                 no_contact_reason1, no_contact_reason2, no_contact_reason3, no_contact_reason4, no_contact_reason5,
                 no_contact_reason6, no_contact_reason7, no_contact_reason8, no_contact_reason9, no_contact_reason10,
                 no_contact_reason11, no_contact_reason12, no_contact_reason13, no_contact_reason14,
                 no_contact_reason15, no_contact_reason16, no_contact_reason17, no_contact_reason18,
                 no_contact_reason19, no_contact_reason20, no_contact_reason21, no_contact_reason22,
                 no_contact_reason23, no_contact_reason24, no_contact_reason25, no_contact_reason26,
                 no_contact_reason27, no_contact_reason28, no_contact_reason29, no_contact_reason30,
                 no_contact_reason31, no_contact_reason32, no_contact_reason33, no_contact_reason34,
                 no_contact_reason35, no_contact_reason36, no_contact_reason37, no_contact_reason38,
                 no_contact_reason39, no_contact_reason40, no_contact_reason41, no_contact_reason42,
                 no_contact_reason43, no_contact_reason44, no_contact_reason45, no_contact_reason46,
                 no_contact_reason47, no_contact_reason48, no_contact_reason49, no_contact_reason50)
dim(person)

eip24 <- select(eip24, -mrn, -dob, 
               -race___1, -race___2, -race___3, -race___4, -race___5, 
               -race___6, -ethnicity,
               -sex_raised, -sex_selfdefined, -insurance, -address_county,
               -address_zip_code,
               -followup_date1, -followup_date2, -followup_date3, -followup_date4,
               -followup_date5, -followup_date6, -followup_date7, -followup_date8,
               -followup_date9, -followup_date10, -followup_date11, -followup_date12,
               -followup_date13, -followup_date14, -followup_date15, -followup_date16,
               -followup_date17, -followup_date18, -followup_date19, -followup_date20,
               -followup_date21, -followup_date22, -followup_date23, -followup_date24,
               -followup_date25, -followup_date26, -followup_date27, -followup_date28,
               -followup_date29, -followup_date30, -followup_date31, -followup_date32,
               -followup_date33, -followup_date34, -followup_date35, -followup_date36,
               -followup_date37, -followup_date38, -followup_date39, -followup_date40,
               -followup_date41, -followup_date42, -followup_date43, -followup_date44,
               -followup_date45, -followup_date46, -followup_date47, -followup_date48,
               -followup_date49, -followup_date50, -followup_counselor1, -followup_counselor2,
               -followup_counselor3, -followup_counselor4, -followup_counselor5,
               -followup_counselor6, -followup_counselor7, -followup_counselor8,
               -followup_counselor9, -followup_counselor10, -followup_counselor11,
               -followup_counselor12, -followup_counselor13, -followup_counselor14,
               -followup_counselor15, -followup_counselor16, -followup_counselor17,
               -followup_counselor18, -followup_counselor19, -followup_counselor20,
               -followup_counselor21, -followup_counselor22, -followup_counselor23,
               -followup_counselor24, -followup_counselor25, -followup_counselor26,
               -followup_counselor27, -followup_counselor28, -followup_counselor29,
               -followup_counselor30, -followup_counselor31, -followup_counselor32,
               -followup_counselor33, -followup_counselor34, -followup_counselor35,
               -followup_counselor36, -followup_counselor37, -followup_counselor38,
               -followup_counselor39, -followup_counselor40, -followup_counselor41,
               -followup_counselor42, -followup_counselor43, -followup_counselor44,
               -followup_counselor45, -followup_counselor46, -followup_counselor47,
               -followup_counselor48, -followup_counselor49, -followup_counselor50,
               -ltc_service1___8, -ltc_service2___8,
               -ltc_service3___8, -ltc_service4___8, -ltc_service5___8,
               -ltc_service6___8, -ltc_service7___8, -ltc_service8___8,
               -ltc_service9___8, -ltc_service10___8, -ltc_service11___8,
               -ltc_service12___8, -ltc_service13___8, -ltc_service14___8,
               -ltc_service15___8, -ltc_service16___8, -ltc_service17___8,
               -ltc_service18___8, -ltc_service19___8, -ltc_service20___8,
               -ltc_service21___8, -ltc_service22___8, -ltc_service23___8,
               -ltc_service24___8, -ltc_service25___8, -ltc_service26___8,
               -ltc_service27___8, -ltc_service28___8, -ltc_service29___8,
               -ltc_service30___8, -ltc_service31___8, -ltc_service32___8,
               -ltc_service33___8, -ltc_service34___8, -ltc_service35___8,
               -ltc_service36___8, -ltc_service37___8, -ltc_service38___8,
               -ltc_service39___8, -ltc_service40___8, -ltc_service41___8,
               -ltc_service42___8, -ltc_service43___8, -ltc_service44___8,
               -ltc_service45___8, -ltc_service46___8, -ltc_service47___8,
               -ltc_service48___8, -ltc_service49___8, -ltc_service50___8,
               -naccho_contact_day1, -naccho_contact_day2,
               -naccho_contact_day3, -naccho_contact_day4, -naccho_contact_day5,
               -naccho_contact_day6, -naccho_contact_day7, -naccho_contact_day8,
               -naccho_contact_day9, -naccho_contact_day10, -naccho_contact_day11,
               -naccho_contact_day12, -naccho_contact_day13, -naccho_contact_day14,
               -naccho_contact_day15, -naccho_contact_day16, -naccho_contact_day17,
               -naccho_contact_day18, -naccho_contact_day19, -naccho_contact_day20,
               -naccho_contact_day21, -naccho_contact_day22, -naccho_contact_day23,
               -naccho_contact_day24, -naccho_contact_day25, -naccho_contact_day26,
               -naccho_contact_day27, -naccho_contact_day28, -naccho_contact_day29,
               -naccho_contact_day30, -naccho_contact_day31, -naccho_contact_day32,
               -naccho_contact_day33, -naccho_contact_day34, -naccho_contact_day35,
               -naccho_contact_day36, -naccho_contact_day37, -naccho_contact_day38,
               -naccho_contact_day39, -naccho_contact_day40, -naccho_contact_day41,
               -naccho_contact_day42, -naccho_contact_day43, -naccho_contact_day44,
               -naccho_contact_day45, -naccho_contact_day46, -naccho_contact_day47,
               -naccho_contact_day48, -naccho_contact_day49, -naccho_contact_day50,
               -naccho_contact_confirm_tx1, -naccho_contact_confirm_tx2,
               -naccho_contact_confirm_tx3, -naccho_contact_confirm_tx4, -naccho_contact_confirm_tx5,
               -naccho_contact_confirm_tx6, -naccho_contact_confirm_tx7, -naccho_contact_confirm_tx8,
               -naccho_contact_confirm_tx9, -naccho_contact_confirm_tx10, -naccho_contact_confirm_tx11,
               -naccho_contact_confirm_tx12, -naccho_contact_confirm_tx13, -naccho_contact_confirm_tx14,
               -naccho_contact_confirm_tx15, -naccho_contact_confirm_tx16, -naccho_contact_confirm_tx17,
               -naccho_contact_confirm_tx18, -naccho_contact_confirm_tx19, -naccho_contact_confirm_tx20,
               -naccho_contact_confirm_tx21, -naccho_contact_confirm_tx22, -naccho_contact_confirm_tx23,
               -naccho_contact_confirm_tx24, -naccho_contact_confirm_tx25, -naccho_contact_confirm_tx26,
               -naccho_contact_confirm_tx27, -naccho_contact_confirm_tx28, -naccho_contact_confirm_tx29,
               -naccho_contact_confirm_tx30, -naccho_contact_confirm_tx31, -naccho_contact_confirm_tx32,
               -naccho_contact_confirm_tx33, -naccho_contact_confirm_tx34, -naccho_contact_confirm_tx35,
               -naccho_contact_confirm_tx36, -naccho_contact_confirm_tx37, -naccho_contact_confirm_tx38,
               -naccho_contact_confirm_tx39, -naccho_contact_confirm_tx40, -naccho_contact_confirm_tx41,
               -naccho_contact_confirm_tx42, -naccho_contact_confirm_tx43, -naccho_contact_confirm_tx44,
               -naccho_contact_confirm_tx45, -naccho_contact_confirm_tx46, -naccho_contact_confirm_tx47,
               -naccho_contact_confirm_tx48, -naccho_contact_confirm_tx49, -naccho_contact_confirm_tx50,
               -who_initiated_contact1, -who_initiated_contact2, -who_initiated_contact3, -who_initiated_contact4, -who_initiated_contact5,
               -who_initiated_contact6, -who_initiated_contact7, -who_initiated_contact8, -who_initiated_contact9, -who_initiated_contact10,
               -who_initiated_contact11, -who_initiated_contact12, -who_initiated_contact13, -who_initiated_contact14,
               -who_initiated_contact15, -who_initiated_contact16, -who_initiated_contact17, -who_initiated_contact18,
               -who_initiated_contact19, -who_initiated_contact20, -who_initiated_contact21, -who_initiated_contact22,
               -who_initiated_contact23, -who_initiated_contact24, -who_initiated_contact25, -who_initiated_contact26,
               -who_initiated_contact27, -who_initiated_contact28, -who_initiated_contact29, -who_initiated_contact30,
               -who_initiated_contact31, -who_initiated_contact32, -who_initiated_contact33, -who_initiated_contact34,
               -who_initiated_contact35, -who_initiated_contact36, -who_initiated_contact37, -who_initiated_contact38,
               -who_initiated_contact39, -who_initiated_contact40, -who_initiated_contact41, -who_initiated_contact42,
               -who_initiated_contact43, -who_initiated_contact44, -who_initiated_contact45, -who_initiated_contact46,
               -who_initiated_contact47, -who_initiated_contact48, -who_initiated_contact49, -who_initiated_contact50,
               -contact_with1, -contact_with2, -contact_with3, -contact_with4, -contact_with5,
               -contact_with6, -contact_with7, -contact_with8, -contact_with9, -contact_with10,
               -contact_with11, -contact_with12, -contact_with13, -contact_with14,
               -contact_with15, -contact_with16, -contact_with17, -contact_with18,
               -contact_with19, -contact_with20, -contact_with21, -contact_with22,
               -contact_with23, -contact_with24, -contact_with25, -contact_with26,
               -contact_with27, -contact_with28, -contact_with29, -contact_with30,
               -contact_with31, -contact_with32, -contact_with33, -contact_with34,
               -contact_with35, -contact_with36, -contact_with37, -contact_with38,
               -contact_with39, -contact_with40, -contact_with41, -contact_with42,
               -contact_with43, -contact_with44, -contact_with45, -contact_with46,
               -contact_with47, -contact_with48, -contact_with49, -contact_with50,
               -ltc_contact1, -ltc_contact2, -ltc_contact3, -ltc_contact4, -ltc_contact5,
               -ltc_contact6, -ltc_contact7, -ltc_contact8, -ltc_contact9, -ltc_contact10,
               -ltc_contact11, -ltc_contact12, -ltc_contact13, -ltc_contact14, -ltc_contact15,
               -ltc_contact16, -ltc_contact17, -ltc_contact18, -ltc_contact19, -ltc_contact20,
               -ltc_contact21, -ltc_contact22, -ltc_contact23, -ltc_contact24, -ltc_contact25,
               -ltc_contact26, -ltc_contact27, -ltc_contact28, -ltc_contact29, -ltc_contact30,
               -ltc_contact31, -ltc_contact32, -ltc_contact33, -ltc_contact34, -ltc_contact35,
               -ltc_contact36, -ltc_contact37, -ltc_contact38, -ltc_contact39, -ltc_contact40,
               -ltc_contact41, -ltc_contact42, -ltc_contact43, -ltc_contact44, -ltc_contact45,
               -ltc_contact46, -ltc_contact47, -ltc_contact48, -ltc_contact49, -ltc_contact50,
               -no_contact_reason1, -no_contact_reason2, -no_contact_reason3, -no_contact_reason4, -no_contact_reason5,
               -no_contact_reason6, -no_contact_reason7, -no_contact_reason8, -no_contact_reason9, -no_contact_reason10,
               -no_contact_reason11, -no_contact_reason12, -no_contact_reason13, -no_contact_reason14,
               -no_contact_reason15, -no_contact_reason16, -no_contact_reason17, -no_contact_reason18,
               -no_contact_reason19, -no_contact_reason20, -no_contact_reason21, -no_contact_reason22,
               -no_contact_reason23, -no_contact_reason24, -no_contact_reason25, -no_contact_reason26,
               -no_contact_reason27, -no_contact_reason28, -no_contact_reason29, -no_contact_reason30,
               -no_contact_reason31, -no_contact_reason32, -no_contact_reason33, -no_contact_reason34,
               -no_contact_reason35, -no_contact_reason36, -no_contact_reason37, -no_contact_reason38,
               -no_contact_reason39, -no_contact_reason40, -no_contact_reason41, -no_contact_reason42,
               -no_contact_reason43, -no_contact_reason44, -no_contact_reason45, -no_contact_reason46,
               -no_contact_reason47, -no_contact_reason48, -no_contact_reason49, -no_contact_reason50)

# Merge person dataset with full eip24 dataset

dim(eip24)
dim(person)
eip24 <- merge(eip24, person, by='record_id', all.x=T)
dim(eip24)
eip24 <- distinct(eip24)
dim(eip24)

```

``` {r Combining Datasets, include=FALSE}

### Combine 2023/2024 Data

dim(eip23)
dim(eip24)


# Changing variables that were changed in 2024 dataset
names(eip23)[names(eip23) == 'encounter_location'] <- 'enc_location'
names(eip23)[names(eip23) == 'encounter_location_other'] <- 'enc_location_other'
names(eip23)[names(eip23) == 'counselor_ref_hiv_specific___4'] <- 'counselor_ref_hiv_specific___0'
names(eip23)[names(eip23) == 'counselor_ref_hcv_specific___2'] <- 'counselor_ref_hcv_specific___0'
names(eip23)[names(eip23) == 'counselor_ref_peer_specific___3'] <- 'counselor_ref_peer_specific___0'
names(eip23)[names(eip23) == 'counselor_ref_mh_specific___3'] <- 'counselor_ref_mh_specific___0'
names(eip23)[names(eip23) == 'counselor_ref_sud_specific___11'] <- 'counselor_ref_sud_specific___0'
names(eip23)[names(eip23) == 'counselor_ref_sti_specific___3'] <- 'counselor_ref_sti_specific___0'
names(eip23)[names(eip23) == 'counselor_ref_housing_specific___8'] <- 'counselor_ref_housing_specific___0'
names(eip23)[names(eip23) == 'counselor_ref_ht_specific___99'] <- 'counselor_ref_ht_specific___0'
names(eip23)[names(eip23) == 'counselor_ref_personabuse_specific___5'] <- 'counselor_ref_personabuse_specific___0'
names(eip23)[names(eip23) == 'counselor_ref_general_specific___6'] <- 'counselor_ref_general_specific___0'
names(eip23)[names(eip23) == 'counselor_ref_food_specific___3'] <- 'counselor_ref_food_specific___0'
names(eip23)[names(eip23) == 'counselor_ref_financial_specific___2'] <- 'counselor_ref_financial_specific___0'
names(eip23)[names(eip23) == 'ltc_service1___5'] <- 'ltc_service1___0'
names(eip23)[names(eip23) == 'ltc_service10___5'] <- 'ltc_service10___0'
names(eip23)[names(eip23) == 'ltc_service11___5'] <- 'ltc_service11___0'
names(eip23)[names(eip23) == 'ltc_service12___5'] <- 'ltc_service12___0'
names(eip23)[names(eip23) == 'ltc_service13___5'] <- 'ltc_service13___0'
names(eip23)[names(eip23) == 'ltc_service14___5'] <- 'ltc_service14___0'
names(eip23)[names(eip23) == 'ltc_service15___5'] <- 'ltc_service15___0'
names(eip23)[names(eip23) == 'ltc_service16___5'] <- 'ltc_service16___0'
names(eip23)[names(eip23) == 'ltc_service17___5'] <- 'ltc_service17___0'
names(eip23)[names(eip23) == 'ltc_service18___5'] <- 'ltc_service18___0'
names(eip23)[names(eip23) == 'ltc_service19___5'] <- 'ltc_service19___0'
names(eip23)[names(eip23) == 'ltc_service2___5'] <- 'ltc_service2___0'
names(eip23)[names(eip23) == 'ltc_service20___5'] <- 'ltc_service20___0'
names(eip23)[names(eip23) == 'ltc_service21___5'] <- 'ltc_service21___0'
names(eip23)[names(eip23) == 'ltc_service22___5'] <- 'ltc_service22___0'
names(eip23)[names(eip23) == 'ltc_service23___5'] <- 'ltc_service23___0'
names(eip23)[names(eip23) == 'ltc_service24___5'] <- 'ltc_service24___0'
names(eip23)[names(eip23) == 'ltc_service25___5'] <- 'ltc_service25___0'
names(eip23)[names(eip23) == 'ltc_service26___5'] <- 'ltc_service26___0'
names(eip23)[names(eip23) == 'ltc_service27___5'] <- 'ltc_service27___0'
names(eip23)[names(eip23) == 'ltc_service28___5'] <- 'ltc_service28___0'
names(eip23)[names(eip23) == 'ltc_service29___5'] <- 'ltc_service29___0'
names(eip23)[names(eip23) == 'ltc_service3___5'] <- 'ltc_service3___0'
names(eip23)[names(eip23) == 'ltc_service30___5'] <- 'ltc_service30___0'
names(eip23)[names(eip23) == 'ltc_service31___5'] <- 'ltc_service31___0'
names(eip23)[names(eip23) == 'ltc_service32___5'] <- 'ltc_service32___0'
names(eip23)[names(eip23) == 'ltc_service33___5'] <- 'ltc_service33___0'
names(eip23)[names(eip23) == 'ltc_service34___5'] <- 'ltc_service34___0'
names(eip23)[names(eip23) == 'ltc_service35___5'] <- 'ltc_service35___0'
names(eip23)[names(eip23) == 'ltc_service36___5'] <- 'ltc_service36___0'
names(eip23)[names(eip23) == 'ltc_service37___5'] <- 'ltc_service37___0'
names(eip23)[names(eip23) == 'ltc_service38___5'] <- 'ltc_service38___0'
names(eip23)[names(eip23) == 'ltc_service39___5'] <- 'ltc_service39___0'
names(eip23)[names(eip23) == 'ltc_service4___5'] <- 'ltc_service4___0'
names(eip23)[names(eip23) == 'ltc_service40___5'] <- 'ltc_service40___0'
names(eip23)[names(eip23) == 'ltc_service41___5'] <- 'ltc_service41___0'
names(eip23)[names(eip23) == 'ltc_service42___5'] <- 'ltc_service42___0'
names(eip23)[names(eip23) == 'ltc_service43___5'] <- 'ltc_service43___0'
names(eip23)[names(eip23) == 'ltc_service44___5'] <- 'ltc_service44___0'
names(eip23)[names(eip23) == 'ltc_service45___5'] <- 'ltc_service45___0'
names(eip23)[names(eip23) == 'ltc_service46___5'] <- 'ltc_service46___0'
names(eip23)[names(eip23) == 'ltc_service47___5'] <- 'ltc_service47___0'
names(eip23)[names(eip23) == 'ltc_service48___5'] <- 'ltc_service48___0'
names(eip23)[names(eip23) == 'ltc_service49___5'] <- 'ltc_service49___0'
names(eip23)[names(eip23) == 'ltc_service5___5'] <- 'ltc_service5___0'
names(eip23)[names(eip23) == 'ltc_service50___5'] <- 'ltc_service50___0'
names(eip23)[names(eip23) == 'ltc_service6___5'] <- 'ltc_service6___0'
names(eip23)[names(eip23) == 'ltc_service7___5'] <- 'ltc_service7___0'
names(eip23)[names(eip23) == 'ltc_service8___5'] <- 'ltc_service8___0'
names(eip23)[names(eip23) == 'ltc_service9___5'] <- 'ltc_service9___0'
names(eip23)[names(eip23) == 'additional_services___99'] <- 'additional_services___0'

eip23$final_test_status_hcv[eip23$final_test_status_hcv == 3] <- 4


# Adding variables introduced in 2024 to 2023 dataset as blank values
eip23$staff_start_peer <- ''
eip23$date_start_peer <- ''
eip23$peer_referred_by <- ''
eip23$peer_reason_for_offer_category <- ''
eip23$peer_reason_for_offer_self_req___1 <- ''
eip23$peer_reason_for_offer_self_req___2 <- ''
eip23$peer_reason_for_offer_self_req___3 <- ''
eip23$peer_reason_for_offer_self_req___5 <- ''
eip23$peer_reason_for_offer_self_req___6 <- ''
eip23$peer_reason_for_offer_self_req___7 <- ''
eip23$peer_reason_for_offer_self_req___8 <- ''
eip23$peer_reason_for_offer_self_req___9 <- ''
eip23$peer_reason_for_offer_self_req___4 <- ''
eip23$peer_reason_for_offer_routine_freq <- ''
eip23$peer_reason_for_offer_self_req_other <- ''
eip23$peer_reason_for_offer_diagnostic___1 <- ''
eip23$peer_reason_for_offer_diagnostic___2 <- ''
eip23$peer_reason_for_offer_diagnostic___3 <- ''
eip23$peer_reason_for_offer_diagnostic___4 <- ''
eip23$peer_reason_for_offer_diagnostic___5 <- ''
eip23$peer_reason_for_offer_diagnostic___6 <- ''
eip23$peer_reason_for_offer_diagnostic___7 <- ''
eip23$peer_reason_for_offer_diagnostic___8 <- ''
eip23$peer_reason_for_offer_diagnostic___9 <- ''
eip23$peer_reason_for_offer_diagnostic___10 <- ''
eip23$peer_reason_for_offer_diagnostic___11 <- ''
eip23$peer_reason_for_offer_diagnostic___12 <- ''
eip23$peer_reason_for_offer_diagnostic___13 <- ''
eip23$peer_reason_for_offer_diagnostic___14 <- ''
eip23$peer_reason_for_offer_diagnostic___15 <- ''
eip23$peer_reason_for_offer_diagnostic___16 <- ''
eip23$peer_reason_for_offer_diagnostic___17 <- ''
eip23$peer_reason_for_offer_diagnostic___18 <- ''
eip23$peer_reason_for_offer_diagnostic___19 <- ''
eip23$peer_reason_for_offer_diagnostic___20 <- ''
eip23$peer_reason_for_offer_diagnostic___21 <- ''
eip23$peer_reason_for_offer_diagnostic___22 <- ''
eip23$peer_reason_for_offer_diagnostic___23 <- ''
eip23$peer_reason_for_offer_diagnostic___24 <- ''
eip23$peer_reason_for_offer_diagnostic___25 <- ''
eip23$peer_reason_for_offer_diagnostic___26 <- ''
eip23$peer_reason_for_offer_diagnostic___27 <- ''
eip23$peer_reason_for_offer_diagnostic___28 <- ''
eip23$peer_reason_for_offer_diagnostic___29 <- ''
eip23$peer_reason_for_offer_diagnostic___30 <- ''
eip23$peer_reason_for_offer_diagnostic___31 <- ''
eip23$peer_reason_for_offer_diagnostic___32 <- ''
eip23$peer_reason_for_offer_diagnostic___33 <- ''
eip23$peer_reason_for_offer_diagnostic_other <- ''
eip23$peer_reason_for_offer_clinical___1 <- ''
eip23$peer_reason_for_offer_clinical___2 <- ''
eip23$peer_reason_for_offer_clinical___3 <- ''
eip23$peer_reason_for_offer_clinical___4 <- ''
eip23$peer_reason_for_offer_clinical___5 <- ''
eip23$peer_reason_for_offer_clinical___7 <- ''
eip23$peer_reason_for_offer_clinical___8 <- ''
eip23$peer_reason_for_offer_clinical___9 <- ''
eip23$peer_reason_for_offer_clinical___10 <- ''
eip23$peer_reason_for_offer_clinical___11 <- ''
eip23$peer_reason_for_offer_clinical___12 <- ''
eip23$peer_reason_for_offer_clinical___13 <- ''
eip23$peer_reason_for_offer_clinical___14 <- ''
eip23$peer_reason_for_offer_clinical___15 <- ''
eip23$peer_reason_for_offer_clinical___16 <- ''
eip23$peer_reason_for_offer_clinical___17 <- ''
eip23$peer_reason_for_offer_clinical___18 <- ''
eip23$peer_reason_for_offer_clinical___19 <- ''
eip23$peer_reason_for_offer_clinical___20 <- ''
eip23$peer_reason_for_offer_clinical___21 <- ''
eip23$peer_reason_for_offer_clinical___22 <- ''
eip23$peer_reason_for_offer_clinical___23 <- ''
eip23$peer_reason_for_offer_clinical___24 <- ''
eip23$peer_reason_for_offer_clinical___25 <- ''
eip23$peer_reason_for_offer_clinical___26 <- ''
eip23$peer_reason_for_offer_clinical___27 <- ''
eip23$peer_reason_for_offer_clinical___28 <- ''
eip23$peer_reason_for_offer_clinical___29 <- ''
eip23$peer_reason_for_offer_clinical___30 <- ''
eip23$peer_reason_for_offer_clinical___31 <- ''
eip23$peer_reason_for_offer_clinical_other <- ''
eip23$peer_reason_for_offer_counselor___1 <- ''
eip23$peer_reason_for_offer_counselor___2 <- ''
eip23$peer_reason_for_offer_counselor___3 <- ''
eip23$peer_reason_for_offer_counselor___4 <- ''
eip23$peer_reason_for_offer_counselor___5 <- ''
eip23$peer_reason_for_offer_counselor___6 <- ''
eip23$peer_reason_for_offer_counselor___7 <- ''
eip23$peer_reason_for_offer_counselor___8 <- ''
eip23$peer_reason_for_offer_counselor___9 <- ''
eip23$peer_reason_for_offer_counselor___10 <- ''
eip23$peer_reason_for_offer_counselor___11 <- ''
eip23$peer_reason_for_offer_counselor___12 <- ''
eip23$peer_reason_for_offer_counselor___13 <- ''
eip23$peer_reason_for_offer_counselor___14 <- ''
eip23$peer_reason_for_offer_counselor___15 <- ''
eip23$peer_reason_for_offer_counselor___16 <- ''
eip23$peer_reason_for_offer_counselor___17 <- ''
eip23$peer_reason_for_offer_counselor___18 <- ''
eip23$peer_reason_for_offer_counselor___19 <- ''
eip23$peer_reason_for_offer_counselor___20 <- ''
eip23$peer_reason_for_offer_counselor___21 <- ''
eip23$peer_reason_for_offer_counselor___22 <- ''
eip23$peer_reason_for_offer_counselor___23 <- ''
eip23$peer_reason_for_offer_counselor___24 <- ''
eip23$peer_reason_for_offer_counselor___25 <- ''
eip23$peer_reason_for_offer_counselor___26 <- ''
eip23$peer_reason_for_offer_counselor___27 <- ''
eip23$peer_reason_for_offer_counselor___28 <- ''
eip23$peer_reason_for_offer_counselor___29 <- ''
eip23$peer_reason_for_offer_counselor___30 <- ''
eip23$peer_reason_for_offer_counselor_other <- ''
eip23$peer_reason_for_offer_demographics___1 <- ''
eip23$peer_reason_for_offer_demographics___2 <- ''
eip23$peer_reason_for_offer_demographics___3 <- ''
eip23$peer_reason_for_offer_demographics___4 <- ''
eip23$peer_reason_for_offer_tnt___1 <- ''
eip23$peer_reason_for_offer_tnt___2 <- ''
eip23$peer_reason_for_offer_tnt___3 <- ''
eip23$peer_reason_for_offer_tnt_number <- ''
eip23$peer_reason_for_offer_tnt_relation <- ''
eip23$offer_outcome_time_peer <- ''
eip23$offer_outcome_location_peer <- ''
eip23$offer_outcome_room_peer <- ''
eip23$offer_outcome_approach_peer___1 <- ''
eip23$offer_outcome_approach_peer___2 <- ''
eip23$offer_outcome_approach_peer___3 <- ''
eip23$offer_outcome_approach_peer___4 <- ''
eip23$offer_outcome_approach_peer___5 <- ''
eip23$offer_outcome_approach_peer___6 <- ''
eip23$offer_outcome_approach_peer___7 <- ''
eip23$offer_outcome_approach_peer___8 <- ''
eip23$offer_outcome_peer <- ''
eip23$offer_outcome_declined_peer___1 <- ''
eip23$offer_outcome_declined_peer___2 <- ''
eip23$offer_outcome_declined_peer___3 <- ''
eip23$offer_outcome_declined_peer___4 <- ''
eip23$offer_outcome_declined_peer___5 <- ''
eip23$offer_outcome_declined_peer___6 <- ''
eip23$offer_outcome_declined_peer___7 <- ''
eip23$offer_outcome_declined_peer___8 <- ''
eip23$offer_outcome_declined_peer___9 <- ''
eip23$offer_outcome_declined_peer___10 <- ''
eip23$offer_outcome_declined_peer___11 <- ''
eip23$offer_outcome_declined_peer___12 <- ''
eip23$offer_outcome_declined_peer___13 <- ''
eip23$offer_outcome_declined_peer___14 <- ''
eip23$offer_outcome_declined_peer___15 <- ''
eip23$offer_outcome_declined_peer___16 <- ''
eip23$offer_outcome_declined_peer___17 <- ''
eip23$offer_outcome_declined_peer___18 <- ''
eip23$offer_outcome_declined_peer___19 <- ''
eip23$offer_outcome_declined_peer___20 <- ''
eip23$offer_outcome_declined_peer___21 <- ''
eip23$offer_outcome_declined_peer___22 <- ''
eip23$offer_outcome_declined_peer___23 <- ''
eip23$offer_outcome_declined_peer___24 <- ''
eip23$offer_outcome_declined_peer___25 <- ''
eip23$offer_outcome_declined_peer___26 <- ''
eip23$offer_outcome_declined_other_peer <- ''
eip23$offer_outcome_prevented_peer___1 <- ''
eip23$offer_outcome_prevented_peer___2 <- ''
eip23$offer_outcome_prevented_peer___3 <- ''
eip23$offer_outcome_prevented_peer___4 <- ''
eip23$offer_outcome_prevented_peer___5 <- ''
eip23$offer_outcome_prevented_peer___6 <- ''
eip23$offer_outcome_prevented_peer___7 <- ''
eip23$offer_outcome_prevented_peer___8 <- ''
eip23$offer_outcome_prevented_peer___9 <- ''
eip23$offer_outcome_prevented_peer___10 <- ''
eip23$offer_outcome_prevented_other_peer <- ''
eip23$peer_navigator_id___14 <- ''
eip23$peer_navigator_id___67 <- ''
eip23$peer_navigator_id___68 <- ''
eip23$peer_navigator_id___0 <- ''
eip23$peer_navigator_id_other <- ''
eip23$peer_initial_enc_details___1 <- ''
eip23$peer_initial_enc_details___2 <- ''
eip23$peer_initial_enc_details___3 <- ''
eip23$peer_initial_enc_details___4 <- ''
eip23$peer_initial_enc_details___5 <- ''
eip23$peer_initial_enc_details___6 <- ''
eip23$peer_initial_enc_details___7 <- ''
eip23$peer_initial_enc_details___8 <- ''
eip23$peer_initial_enc_details___9 <- ''
eip23$peer_initial_enc_details___10 <- ''
eip23$peer_initial_enc_details___0 <- ''
eip23$peer_initial_enc_details_other <- ''
eip23$peer_initial_enc_comments <- ''
eip23$peer_fu_yn <- ''
eip23$peer_next_fu_date <- ''
eip23$peer_fu_closed <- ''
eip23$peer_support_complete <- ''
eip23$nonmedical_drug_use_ltc <- ''
eip23$drug_difficulty_ltc <- ''
eip23$marijuana_use_ltc <- ''
eip23$cocaine_use_ltc <- ''
eip23$rx_amphetamine_use_ltc <- ''
eip23$meth_use_ltc <- ''
eip23$inhalants_use_ltc <- ''
eip23$sedatives_use_ltc <- ''
eip23$ruffies_use_ltc <- ''
eip23$hallucinogen_use_ltc <- ''
eip23$street_opioid_use_ltc <- ''
eip23$rx_opioid_use_ltc <- ''
eip23$injection_drug_use_ltc <- ''
eip23$share_works_last_ltc <- ''
eip23$other_drug_use_ltc <- ''
eip23$other_drug_ltc <- ''
eip23$idu_calc_ltc <- ''
eip23$shares_works_calc_ltc <- ''
eip23$marijuana_use_3mo_ltc <- ''
eip23$cocaine_use_3mo_ltc <- ''
eip23$rx_amphetamine_use_3mo_ltc <- ''
eip23$meth_use_3mo_ltc <- ''
eip23$inhalants_use_3mo_ltc <- ''
eip23$sedatives_use_3mo_ltc <- ''
eip23$hallucinogen_use_3mo_ltc <- ''
eip23$street_opioid_use_3mo_ltc <- ''
eip23$rx_opioid_use_3mo_ltc <- ''
eip23$other_drug_use_3mo_ltc <- ''
eip23$marijuana_use_urge_ltc <- ''
eip23$cocaine_use_urge_ltc <- ''
eip23$meth_use_urge_ltc <- ''
eip23$rx_amphetamine_use_urge_ltc <- ''
eip23$inhalants_use_urge_ltc <- ''
eip23$sedatives_use_urge_ltc <- ''
eip23$hallucinogen_use_urge_ltc <- ''
eip23$street_opioid_use_urge_ltc <- ''
eip23$rx_opioid_use_urge_ltc <- ''
eip23$other_drug_use_urge_ltc <- ''
eip23$marijuana_use_probs_ltc <- ''
eip23$cocaine_use_probs_ltc <- ''
eip23$rx_amphetamine_use_probs_ltc <- ''
eip23$meth_use_probs_ltc <- ''
eip23$inhalants_use_probs_ltc <- ''
eip23$sedatives_use_probs_ltc <- ''
eip23$hallucinogen_use_probs_ltc <- ''
eip23$street_opioid_use_probs_ltc <- ''
eip23$rx_opioid_use_probs_ltc <- ''
eip23$other_drug_use_probs_ltc <- ''
eip23$marijuana_use_failed_ltc <- ''
eip23$cocaine_use_failed_ltc <- ''
eip23$rx_amphetamine_use_failed_ltc <- ''
eip23$meth_use_failed_ltc <- ''
eip23$inhalants_use_failed_ltc <- ''
eip23$sedatives_use_failed_ltc <- ''
eip23$hallucinogen_use_failed_ltc <- ''
eip23$street_opioid_use_failed_ltc <- ''
eip23$rx_opioid_use_failed_ltc <- ''
eip23$other_drug_use_failed_ltc <- ''
eip23$marijuana_use_concern_ltc <- ''
eip23$cocaine_use_concern_ltc <- ''
eip23$rx_amphetamine_use_concern_ltc <- ''
eip23$meth_use_concern_ltc <- ''
eip23$inhalants_use_concern_ltc <- ''
eip23$sedatives_use_concern_ltc <- ''
eip23$hallucinogen_use_concern_ltc <- ''
eip23$street_opioid_use_concern_ltc <- ''
eip23$rx_opioid_use_concern_ltc <- ''
eip23$other_drug_use_concern_ltc <- ''
eip23$marijuana_use_tried_stop_ltc <- ''
eip23$cocaine_use_tried_stop_ltc <- ''
eip23$rx_amphetamine_use_tried_stop_ltc <- ''
eip23$meth_use_tried_stop_ltc <- ''
eip23$inhalants_use_tried_stop_ltc <- ''
eip23$sedatives_use_tried_stop_ltc <- ''
eip23$hallucinogen_use_tried_stop_ltc <- ''
eip23$street_opioid_use_tried_stop_ltc <- ''
eip23$rx_opioid_use_tried_stop_ltc <- ''
eip23$other_drug_use_tried_stop_ltc <- ''
eip23$assist_score_ltc <- ''
eip23$marijuana_score_ltc <- ''
eip23$cocaine_score_ltc <- ''
eip23$rx_amphetamine_score_ltc <- ''
eip23$meth_score_ltc <- ''
eip23$inhalants_score_ltc <- ''
eip23$sedatives_score_ltc <- ''
eip23$hallucinogen_score_ltc <- ''
eip23$street_opioid_score_ltc <- ''
eip23$rx_opioid_score_ltc <- ''
eip23$other_drug_score_ltc <- ''
eip23$marijuana_pos_ltc <- ''
eip23$cocaine_pos_ltc <- ''
eip23$rx_amphetamine_pos_ltc <- ''
eip23$meth_pos_ltc <- ''
eip23$inhalants_pos_ltc <- ''
eip23$sedatives_pos_ltc <- ''
eip23$hallucinogen_pos_ltc <- ''
eip23$street_opioid_pos_ltc <- ''
eip23$rx_opioid_pos_ltc <- ''
eip23$other_drug_pos_ltc <- ''
eip23$assist_pos_ltc <- ''
eip23$sud_screen_positive_ltc <- ''
eip23$ltc_hcv_referral_uc_pharmacy_date <- ''
eip23$ltc_sud_referral_decoach_date <- ''
eip23$ltc_mh_referral_charlie_date <- ''
eip23$ltc_mh_referral_lighthouse_date <- ''
eip23$ltc_mh_referral_mindpeace_date <- ''
eip23$ltc_mh_referral_probono_date <- ''
eip23$ltc_housing_referral_freestore_date <- ''
eip23$ltc_housing_referral_lighthouse_date <- ''
eip23$ltc_food_referral_our_savior_date <- ''
eip23$ltc_food_referral_evanston_date <- ''
eip23$ltc_food_referral_fairhaven_date <- ''
eip23$ltc_food_referral_healthy_harvest_date <- ''
eip23$ltc_food_referral_prince_date <- ''
eip23$ltc_food_referral_united_date <- ''
eip23$ltc_financial_referral_freestore_date <- ''
eip23$ltc_financial_referral_welcome_home_nky_date <- ''
eip23$ltc_financial_referral_freestore___1 <- ''
eip23$ltc_financial_referral_freestore___2 <- ''
eip23$ltc_financial_referral_freestore___3 <- ''
eip23$ltc_financial_referral_welcome_home_nky___1 <- ''
eip23$ltc_financial_referral_welcome_home_nky___2 <- ''
eip23$ltc_financial_referral_welcome_home_nky___3 <- ''
eip23$ltc_food_referral_evanston___1 <- ''
eip23$ltc_food_referral_evanston___2 <- ''
eip23$ltc_food_referral_evanston___3 <- ''
eip23$ltc_food_referral_fairhaven___1 <- ''
eip23$ltc_food_referral_fairhaven___2 <- ''
eip23$ltc_food_referral_fairhaven___3 <- ''
eip23$ltc_food_referral_healthy_harvest___1 <- ''
eip23$ltc_food_referral_healthy_harvest___2 <- ''
eip23$ltc_food_referral_healthy_harvest___3 <- ''
eip23$ltc_food_referral_our_savior___1 <- ''
eip23$ltc_food_referral_our_savior___2 <- ''
eip23$ltc_food_referral_our_savior___3 <- ''
eip23$ltc_food_referral_prince___1 <- ''
eip23$ltc_food_referral_prince___2 <- ''
eip23$ltc_food_referral_prince___3 <- ''
eip23$ltc_food_referral_united___1 <- ''
eip23$ltc_food_referral_united___2 <- ''
eip23$ltc_food_referral_united___3 <- ''
eip23$ltc_hcv_referral_uc_pharmacy___1 <- ''
eip23$ltc_hcv_referral_uc_pharmacy___2 <- ''
eip23$ltc_hcv_referral_uc_pharmacy___3 <- ''
eip23$ltc_hcv_referral_uc_pharmacy_telehealth___1 <- ''
eip23$ltc_hcv_referral_uc_pharmacy_telehealth___2 <- ''
eip23$ltc_hcv_referral_uc_pharmacy_telehealth___3 <- ''
eip23$ltc_housing_referral_freestore___1 <- ''
eip23$ltc_housing_referral_freestore___2 <- ''
eip23$ltc_housing_referral_freestore___3 <- ''
eip23$ltc_housing_referral_lighthouse___1 <- ''
eip23$ltc_housing_referral_lighthouse___2 <- ''
eip23$ltc_housing_referral_lighthouse___3 <- ''
eip23$ltc_mh_referral_charlie___1 <- ''
eip23$ltc_mh_referral_charlie___2 <- ''
eip23$ltc_mh_referral_charlie___3 <- ''
eip23$ltc_mh_referral_lighthouse___1 <- ''
eip23$ltc_mh_referral_lighthouse___2 <- ''
eip23$ltc_mh_referral_lighthouse___3 <- ''
eip23$ltc_mh_referral_mindpeace___1 <- ''
eip23$ltc_mh_referral_mindpeace___2 <- ''
eip23$ltc_mh_referral_mindpeace___3 <- ''
eip23$ltc_mh_referral_probono___1 <- ''
eip23$ltc_mh_referral_probono___2 <- ''
eip23$ltc_mh_referral_probono___3 <- ''
eip23$ltc_sud_referral_decoach___1 <- ''
eip23$ltc_sud_referral_decoach___2 <- ''
eip23$ltc_sud_referral_decoach___3 <- ''
eip23$followup_counselor_other1 <- ''
eip23$followup_counselor_other10 <- ''
eip23$followup_counselor_other11 <- ''
eip23$followup_counselor_other12 <- ''
eip23$followup_counselor_other13 <- ''
eip23$followup_counselor_other14 <- ''
eip23$followup_counselor_other15 <- ''
eip23$followup_counselor_other16 <- ''
eip23$followup_counselor_other17 <- ''
eip23$followup_counselor_other18 <- ''
eip23$followup_counselor_other19 <- ''
eip23$followup_counselor_other2 <- ''
eip23$followup_counselor_other20 <- ''
eip23$followup_counselor_other21 <- ''
eip23$followup_counselor_other22 <- ''
eip23$followup_counselor_other23 <- ''
eip23$followup_counselor_other24 <- ''
eip23$followup_counselor_other25 <- ''
eip23$followup_counselor_other26 <- ''
eip23$followup_counselor_other27 <- ''
eip23$followup_counselor_other28 <- ''
eip23$followup_counselor_other29 <- ''
eip23$followup_counselor_other3 <- ''
eip23$followup_counselor_other30 <- ''
eip23$followup_counselor_other31 <- ''
eip23$followup_counselor_other32 <- ''
eip23$followup_counselor_other33 <- ''
eip23$followup_counselor_other34 <- ''
eip23$followup_counselor_other35 <- ''
eip23$followup_counselor_other36 <- ''
eip23$followup_counselor_other37 <- ''
eip23$followup_counselor_other38 <- ''
eip23$followup_counselor_other39 <- ''
eip23$followup_counselor_other4 <- ''
eip23$followup_counselor_other40 <- ''
eip23$followup_counselor_other41 <- ''
eip23$followup_counselor_other42 <- ''
eip23$followup_counselor_other43 <- ''
eip23$followup_counselor_other44 <- ''
eip23$followup_counselor_other45 <- ''
eip23$followup_counselor_other46 <- ''
eip23$followup_counselor_other47 <- ''
eip23$followup_counselor_other48 <- ''
eip23$followup_counselor_other49 <- ''
eip23$followup_counselor_other5 <- ''
eip23$followup_counselor_other50 <- ''
eip23$followup_counselor_other6 <- ''
eip23$followup_counselor_other7 <- ''
eip23$followup_counselor_other8 <- ''
eip23$followup_counselor_other9 <- ''
eip23$ltc_service_other1 <- ''
eip23$ltc_service_other10 <- ''
eip23$ltc_service_other11 <- ''
eip23$ltc_service_other12 <- ''
eip23$ltc_service_other13 <- ''
eip23$ltc_service_other14 <- ''
eip23$ltc_service_other15 <- ''
eip23$ltc_service_other16 <- ''
eip23$ltc_service_other17 <- ''
eip23$ltc_service_other18 <- ''
eip23$ltc_service_other19 <- ''
eip23$ltc_service_other2 <- ''
eip23$ltc_service_other20 <- ''
eip23$ltc_service_other21 <- ''
eip23$ltc_service_other22 <- ''
eip23$ltc_service_other23 <- ''
eip23$ltc_service_other24 <- ''
eip23$ltc_service_other25 <- ''
eip23$ltc_service_other26 <- ''
eip23$ltc_service_other27 <- ''
eip23$ltc_service_other28 <- ''
eip23$ltc_service_other29 <- ''
eip23$ltc_service_other3 <- ''
eip23$ltc_service_other30 <- ''
eip23$ltc_service_other31 <- ''
eip23$ltc_service_other32 <- ''
eip23$ltc_service_other33 <- ''
eip23$ltc_service_other34 <- ''
eip23$ltc_service_other35 <- ''
eip23$ltc_service_other36 <- ''
eip23$ltc_service_other37 <- ''
eip23$ltc_service_other38 <- ''
eip23$ltc_service_other39 <- ''
eip23$ltc_service_other4 <- ''
eip23$ltc_service_other40 <- ''
eip23$ltc_service_other41 <- ''
eip23$ltc_service_other42 <- ''
eip23$ltc_service_other43 <- ''
eip23$ltc_service_other44 <- ''
eip23$ltc_service_other45 <- ''
eip23$ltc_service_other46 <- ''
eip23$ltc_service_other47 <- ''
eip23$ltc_service_other48 <- ''
eip23$ltc_service_other49 <- ''
eip23$ltc_service_other5 <- ''
eip23$ltc_service_other50 <- ''
eip23$ltc_service_other6 <- ''
eip23$ltc_service_other7 <- ''
eip23$ltc_service_other8 <- ''
eip23$ltc_service_other9 <- ''
eip23$services1___11 <- ''
eip23$ltc_sud_oud_fu <- ''
eip23$ltc_hcv_dashboard <- ''
eip23$ltc_hcv_initial_contact <- ''
eip23$ltc_coordinator_per_case_other <- ''
eip23$counselor_ref_sud_specific___15 <- ''
eip23$counselor_ref_sud_specific___16 <- ''
eip23$counselor_ref_sud_specific___17 <- ''
eip23$counselor_ref_sud_specific___18 <- ''
eip23$counselor_ref_sud_specific___19 <- ''
eip23$counselor_ref_sud_specific___20 <- ''
eip23$counselor_ref_sud_specific___21 <- ''
eip23$counselor_ref_sud_specific___22 <- ''
eip23$counselor_ref_sud_specific___23 <- ''
eip23$counselor_ref_sud_specific___24 <- ''
eip23$counselor_ref_sud_specific___25 <- ''
eip23$counselor_ref_sud_specific___26 <- ''
eip23$counselor_ref_sud_specific___27 <- ''
eip23$counselor_ref_sud_specific___28 <- ''
eip23$counselor_ref_sud_specific___29 <- ''
eip23$counselor_ref_sud_specific___30 <- ''
eip23$counselor_ref_sud_specific___31 <- ''
eip23$counselor_ref_sud_specific___32 <- ''
eip23$counselor_ref_sud_specific___33 <- ''
eip23$counselor_ref_sud_specific___34 <- ''
eip23$counselor_ref_sud_specific___35 <- ''
eip23$counselor_ref_sud_specific___36 <- ''
eip23$counselor_ref_sud_specific___37 <- ''
eip23$counselor_ref_sud_specific___38 <- ''
eip23$counselor_ref_sud_specific___39 <- ''
eip23$counselor_ref_sud_specific___40 <- ''
eip23$counselor_ref_sud_specific___41 <- ''
eip23$counselor_ref_sud_specific___42 <- ''
eip23$counselor_ref_sud_specific___43 <- ''
eip23$counselor_ref_sud_specific___44 <- ''
eip23$counselor_ref_sud_specific___45 <- ''
eip23$counselor_ref_sud_specific___46 <- ''
eip23$counselor_ref_sud_specific___47 <- ''
eip23$counselor_ref_sud_specific___48 <- ''
eip23$counselor_ref_sud_specific___49 <- ''
eip23$counselor_ref_sud_specific___50 <- ''
eip23$counselor_ref_sud_specific___51 <- ''
eip23$counselor_ref_sud_specific___52 <- ''
eip23$counselor_ref_sud_specific___53 <- ''
eip23$counselor_ref_sud_specific___54 <- ''
eip23$counselor_ref_sud_specific___55 <- ''
eip23$counselor_ref_sud_specific___56 <- ''
eip23$counselor_ref_sud_specific___57 <- ''
eip23$counselor_ref_mh_specific___6 <- ''
eip23$counselor_ref_mh_specific___7 <- ''
eip23$counselor_ref_mh_specific___8 <- ''
eip23$counselor_ref_mh_specific___9 <- ''
eip23$counselor_ref_housing_specific___9 <- ''
eip23$counselor_ref_housing_specific___10 <- ''
eip23$counselor_ref_housing_specific___11 <- ''
eip23$counselor_ref_housing_specific___12 <- ''
eip23$counselor_ref_housing_specific___13 <- ''
eip23$counselor_ref_housing_specific___14 <- ''
eip23$counselor_ref_housing_specific___15 <- ''
eip23$counselor_ref_housing_specific___16 <- ''
eip23$counselor_ref_housing_specific___17 <- ''
eip23$counselor_ref_housing_specific___18 <- ''
eip23$counselor_ref_housing_specific___19 <- ''
eip23$counselor_ref_housing_specific___20 <- ''
eip23$counselor_ref_food_specific___5 <- ''
eip23$counselor_ref_food_specific___6 <- ''
eip23$counselor_ref_food_specific___7 <- ''
eip23$counselor_ref_food_specific___8 <- ''
eip23$counselor_ref_food_specific___9 <- ''
eip23$counselor_ref_food_specific___10 <- ''
eip23$counselor_ref_financial_specific___2 <- ''
eip23$counselor_ref_financial_specific___3 <- ''
eip23$counselor_ref_sud_specific___11 <- ''
eip23$ltc_sud_referral_decoach___0 <- ''
eip23$ltc_hcv_referral_uc_pharmacy_telehealth <- ''
eip23$ltc_coordinator_per_case___77 <- ''
eip23$ltc_coordinator_per_case___78 <- ''
eip23$ltc_coordinator_per_case___79 <- ''
eip23$ltc_coordinator_per_case___80 <- ''
eip23$anderson_ltc_open_calc <- ''
eip23$counselor_ref_sud_specific___58 <- ''
eip23$ltc_sud_referral_pods___0 <- ''
eip23$ltc_sud_referral_pods___1 <- ''
eip23$ltc_sud_referral_pods___2 <- ''
eip23$ltc_sud_referral_pods___3 <- ''
eip23$ltc_sud_referral_pods_date <- ''










eip23$counselor_sti_start <- ''
eip23$datetime_sti_start <- ''
eip23$referred_by_sti <- ''
eip23$reason_for_offer_category_sti_test <- ''
eip23$reason_for_offer_self_req_sti___1 <- ''
eip23$reason_for_offer_self_req_sti___2 <- ''
eip23$reason_for_offer_self_req_sti___3 <- ''
eip23$reason_for_offer_self_req_sti___4 <- ''
eip23$reason_for_offer_self_req_sti___5 <- ''
eip23$reason_for_offer_self_req_sti___6 <- ''
eip23$reason_for_offer_self_req_sti___7 <- ''
eip23$reason_for_offer_self_req_sti___8 <- ''
eip23$reason_for_offer_self_req_sti___9 <- ''
eip23$reason_for_offer_routine_freq_sti <- ''
eip23$reason_for_offer_self_req_other_sti <- ''
eip23$reason_for_offer_diagnostic_sti___1 <- ''
eip23$reason_for_offer_diagnostic_sti___2 <- ''
eip23$reason_for_offer_diagnostic_sti___3 <- ''
eip23$reason_for_offer_diagnostic_sti___4 <- ''
eip23$reason_for_offer_diagnostic_sti___5 <- ''
eip23$reason_for_offer_diagnostic_sti___6 <- ''
eip23$reason_for_offer_diagnostic_sti___7 <- ''
eip23$reason_for_offer_diagnostic_sti___8 <- ''
eip23$reason_for_offer_diagnostic_sti___9 <- ''
eip23$reason_for_offer_diagnostic_sti___10 <- ''
eip23$reason_for_offer_diagnostic_sti___11 <- ''
eip23$reason_for_offer_diagnostic_sti___12 <- ''
eip23$reason_for_offer_diagnostic_sti___13 <- ''
eip23$reason_for_offer_diagnostic_sti___14 <- ''
eip23$reason_for_offer_diagnostic_sti___15 <- ''
eip23$reason_for_offer_diagnostic_sti___16 <- ''
eip23$reason_for_offer_diagnostic_sti___17 <- ''
eip23$reason_for_offer_diagnostic_sti___18 <- ''
eip23$reason_for_offer_diagnostic_sti___19 <- ''
eip23$reason_for_offer_diagnostic_sti___20 <- ''
eip23$reason_for_offer_diagnostic_sti___21 <- ''
eip23$reason_for_offer_diagnostic_sti___22 <- ''
eip23$reason_for_offer_diagnostic_sti___23 <- ''
eip23$reason_for_offer_diagnostic_sti___24 <- ''
eip23$reason_for_offer_diagnostic_sti___25 <- ''
eip23$reason_for_offer_diagnostic_sti___26 <- ''
eip23$reason_for_offer_diagnostic_sti___27 <- ''
eip23$reason_for_offer_diagnostic_sti___28 <- ''
eip23$reason_for_offer_diagnostic_sti___29 <- ''
eip23$reason_for_offer_diagnostic_sti___30 <- ''
eip23$reason_for_offer_diagnostic_sti___31 <- ''
eip23$reason_for_offer_diagnostic_sti___32 <- ''
eip23$reason_for_offer_diagnostic_sti___33 <- ''
eip23$reason_for_offer_diagnostic_other_sti <- ''
eip23$reason_for_offer_clinical_sti___1 <- ''
eip23$reason_for_offer_clinical_sti___2 <- ''
eip23$reason_for_offer_clinical_sti___3 <- ''
eip23$reason_for_offer_clinical_sti___4 <- ''
eip23$reason_for_offer_clinical_sti___5 <- ''
eip23$reason_for_offer_clinical_sti___7 <- ''
eip23$reason_for_offer_clinical_sti___8 <- ''
eip23$reason_for_offer_clinical_sti___9 <- ''
eip23$reason_for_offer_clinical_sti___10 <- ''
eip23$reason_for_offer_clinical_sti___11 <- ''
eip23$reason_for_offer_clinical_sti___12 <- ''
eip23$reason_for_offer_clinical_sti___13 <- ''
eip23$reason_for_offer_clinical_sti___14 <- ''
eip23$reason_for_offer_clinical_sti___15 <- ''
eip23$reason_for_offer_clinical_sti___16 <- ''
eip23$reason_for_offer_clinical_sti___17 <- ''
eip23$reason_for_offer_clinical_sti___18 <- ''
eip23$reason_for_offer_clinical_sti___19 <- ''
eip23$reason_for_offer_clinical_sti___20 <- ''
eip23$reason_for_offer_clinical_sti___21 <- ''
eip23$reason_for_offer_clinical_sti___22 <- ''
eip23$reason_for_offer_clinical_sti___23 <- ''
eip23$reason_for_offer_clinical_sti___24 <- ''
eip23$reason_for_offer_clinical_sti___25 <- ''
eip23$reason_for_offer_clinical_sti___26 <- ''
eip23$reason_for_offer_clinical_sti___27 <- ''
eip23$reason_for_offer_clinical_sti___28 <- ''
eip23$reason_for_offer_clinical_sti___29 <- ''
eip23$reason_for_offer_clinical_sti___30 <- ''
eip23$reason_for_offer_clinical_sti___31 <- ''
eip23$reason_for_offer_clinical_sti___32 <- ''
eip23$reason_for_offer_clinical_other_sti <- ''
eip23$reason_for_offer_counselor_sti___1 <- ''
eip23$reason_for_offer_counselor_sti___2 <- ''
eip23$reason_for_offer_counselor_sti___3 <- ''
eip23$reason_for_offer_counselor_sti___4 <- ''
eip23$reason_for_offer_counselor_sti___5 <- ''
eip23$reason_for_offer_counselor_sti___6 <- ''
eip23$reason_for_offer_counselor_sti___7 <- ''
eip23$reason_for_offer_counselor_sti___8 <- ''
eip23$reason_for_offer_counselor_sti___9 <- ''
eip23$reason_for_offer_counselor_sti___10 <- ''
eip23$reason_for_offer_counselor_sti___11 <- ''
eip23$reason_for_offer_counselor_sti___12 <- ''
eip23$reason_for_offer_counselor_sti___13 <- ''
eip23$reason_for_offer_counselor_sti___14 <- ''
eip23$reason_for_offer_counselor_sti___15 <- ''
eip23$reason_for_offer_counselor_sti___16 <- ''
eip23$reason_for_offer_counselor_sti___17 <- ''
eip23$reason_for_offer_counselor_sti___18 <- ''
eip23$reason_for_offer_counselor_sti___19 <- ''
eip23$reason_for_offer_counselor_sti___20 <- ''
eip23$reason_for_offer_counselor_sti___21 <- ''
eip23$reason_for_offer_counselor_sti___22 <- ''
eip23$reason_for_offer_counselor_sti___23 <- ''
eip23$reason_for_offer_counselor_sti___24 <- ''
eip23$reason_for_offer_counselor_sti___25 <- ''
eip23$reason_for_offer_counselor_sti___26 <- ''
eip23$reason_for_offer_counselor_sti___27 <- ''
eip23$reason_for_offer_counselor_sti___28 <- ''
eip23$reason_for_offer_counselor_sti___29 <- ''
eip23$reason_for_offer_counselor_sti___30 <- ''
eip23$reason_for_offer_counselor_sti___31 <- ''
eip23$reason_for_offer_counselor_other_sti <- ''
eip23$reason_for_offer_demographics_sti___1 <- ''
eip23$reason_for_offer_demographics_sti___2 <- ''
eip23$reason_for_offer_demographics_sti___3 <- ''
eip23$reason_for_offer_demographics_sti___4 <- ''
eip23$reason_for_offer_tnt_sti___1 <- ''
eip23$reason_for_offer_tnt_sti___2 <- ''
eip23$reason_for_offer_tnt_sti___3 <- ''
eip23$reason_for_offer_tnt_number_sti <- ''
eip23$reason_for_offer_tnt_relation_sti <- ''
eip23$offer_outcome_time_sti <- ''
eip23$offer_outcome_location_sti <- ''
eip23$offer_outcome_room_sti <- ''
eip23$offer_outcome_approach_sti___1 <- ''
eip23$offer_outcome_approach_sti___2 <- ''
eip23$offer_outcome_approach_sti___3 <- ''
eip23$offer_outcome_approach_sti___4 <- ''
eip23$offer_outcome_approach_sti___5 <- ''
eip23$offer_outcome_approach_sti___6 <- ''
eip23$offer_outcome_approach_sti___7 <- ''
eip23$offer_outcome_approach_sti___8 <- ''
eip23$offer_outcome_sti <- ''
eip23$offer_outcome_declined_sti___1 <- ''
eip23$offer_outcome_declined_sti___2 <- ''
eip23$offer_outcome_declined_sti___3 <- ''
eip23$offer_outcome_declined_sti___4 <- ''
eip23$offer_outcome_declined_sti___5 <- ''
eip23$offer_outcome_declined_sti___6 <- ''
eip23$offer_outcome_declined_sti___7 <- ''
eip23$offer_outcome_declined_sti___8 <- ''
eip23$offer_outcome_declined_sti___9 <- ''
eip23$offer_outcome_declined_sti___10 <- ''
eip23$offer_outcome_declined_sti___11 <- ''
eip23$offer_outcome_declined_sti___12 <- ''
eip23$offer_outcome_declined_sti___13 <- ''
eip23$offer_outcome_declined_sti___14 <- ''
eip23$offer_outcome_declined_sti___15 <- ''
eip23$offer_outcome_declined_sti___16 <- ''
eip23$offer_outcome_declined_sti___17 <- ''
eip23$offer_outcome_declined_sti___18 <- ''
eip23$offer_outcome_declined_sti___19 <- ''
eip23$offer_outcome_declined_sti___20 <- ''
eip23$offer_outcome_declined_sti___21 <- ''
eip23$offer_outcome_declined_sti___22 <- ''
eip23$offer_outcome_declined_sti___23 <- ''
eip23$offer_outcome_declined_sti___24 <- ''
eip23$offer_outcome_declined_sti___25 <- ''
eip23$offer_outcome_declined_sti___26 <- ''
eip23$offer_outcome_declined_other_sti <- ''
eip23$offer_outcome_prevented_sti___1 <- ''
eip23$offer_outcome_prevented_sti___2 <- ''
eip23$offer_outcome_prevented_sti___3 <- ''
eip23$offer_outcome_prevented_sti___4 <- ''
eip23$offer_outcome_prevented_sti___5 <- ''
eip23$offer_outcome_prevented_sti___6 <- ''
eip23$offer_outcome_prevented_sti___7 <- ''
eip23$offer_outcome_prevented_sti___8 <- ''
eip23$offer_outcome_prevented_sti___9 <- ''
eip23$offer_outcome_prevented_sti___10 <- ''
eip23$offer_outcome_prevented_other_sti <- ''
eip23$sti_test_type1 <- ''
eip23$syph_test_assay1 <- ''
eip23$sti_test_sample1 <- ''
eip23$sti_test_collected1 <- ''
eip23$sti_test_processed1 <- ''
eip23$sample_obtained_sti1 <- ''
eip23$assay_began_sti1 <- ''
eip23$sti_test_processing_location1 <- ''
eip23$sti_test_conv_no1 <- ''
eip23$sti_test_collected_rsn1 <- ''
eip23$sti_test_process_rsn1 <- ''
eip23$assay_read_sti1 <- ''
eip23$sti_result1 <- ''
eip23$sti_result_yn2 <- ''
eip23$sti_test_type2 <- ''
eip23$syph_test_assay2 <- ''
eip23$sti_test_sample2 <- ''
eip23$sti_test_collected2 <- ''
eip23$sti_test_processed2 <- ''
eip23$sample_obtained_sti2 <- ''
eip23$assay_began_sti2 <- ''
eip23$sti_test_processing_location2 <- ''
eip23$sti_test_conv_no2 <- ''
eip23$sti_test_collected_rsn2 <- ''
eip23$sti_test_process_rsn2 <- ''
eip23$assay_read_sti2 <- ''
eip23$sti_result2 <- ''
eip23$sti_result_yn3 <- ''
eip23$sti_test_type3 <- ''
eip23$syph_test_assay3 <- ''
eip23$sti_test_sample3 <- ''
eip23$sti_test_collected3 <- ''
eip23$sti_test_processed3 <- ''
eip23$sample_obtained_sti3 <- ''
eip23$assay_began_sti3 <- ''
eip23$sti_test_processing_location3 <- ''
eip23$sti_test_conv_no3 <- ''
eip23$sti_test_collected_rsn3 <- ''
eip23$sti_test_process_rsn3 <- ''
eip23$assay_read_sti3 <- ''
eip23$sti_result3 <- ''
eip23$sti_result_yn4 <- ''
eip23$sti_test_type4 <- ''
eip23$syph_test_assay4 <- ''
eip23$sti_test_sample4 <- ''
eip23$sti_test_collected4 <- ''
eip23$sti_test_processed4 <- ''
eip23$sample_obtained_sti4 <- ''
eip23$assay_began_sti4 <- ''
eip23$sti_test_collected_rsn4 <- ''
eip23$sti_test_process_rsn4 <- ''
eip23$sti_test_processing_location4 <- ''
eip23$sti_test_conv_no4 <- ''
eip23$assay_read_sti4 <- ''
eip23$sti_result4 <- ''
eip23$sti_result_yn5 <- ''
eip23$sti_test_type5 <- ''
eip23$syph_test_assay5 <- ''
eip23$sti_test_sample5 <- ''
eip23$sti_test_collected5 <- ''
eip23$sti_test_processed5 <- ''
eip23$sample_obtained_sti5 <- ''
eip23$assay_began_sti5 <- ''
eip23$sti_test_collected_rsn5 <- ''
eip23$sti_test_process_rsn5 <- ''
eip23$sti_test_processing_location5 <- ''
eip23$sti_test_conv_no5 <- ''
eip23$assay_read_sti5 <- ''
eip23$sti_result5 <- ''
eip23$sti_result_yn6 <- ''
eip23$sti_test_type6 <- ''
eip23$syph_test_assay6 <- ''
eip23$sti_test_sample6 <- ''
eip23$sti_test_collected6 <- ''
eip23$sti_test_processed6 <- ''
eip23$sample_obtained_sti6 <- ''
eip23$assay_began_sti6 <- ''
eip23$sti_test_collected_rsn6 <- ''
eip23$sti_test_process_rsn6 <- ''
eip23$sti_test_processing_location6 <- ''
eip23$sti_test_conv_no6 <- ''
eip23$assay_read_sti6 <- ''
eip23$sti_result6 <- ''
eip23$final_test_status_syph <- ''
eip23$sti_result_notified_enc_yn <- ''
eip23$result_notification_sti <- ''
eip23$pt_not_notified_sti_reason <- ''
eip23$pt_not_notified_sti_reason_disp <- ''
eip23$pt_not_notified_sti_reason_dc <- ''
eip23$sti_result_notification_fu <- ''
eip23$result_notification_sti_fu <- ''
eip23$testing_sti_complete <- ''
eip23$enc_location_513_bus <- ''
eip23$deshpande_ltc_open_calc <- ''
eip23$peer_intern <- ''


# Adding variables removed from 2023 dataset to 2024 dataset as blank values
eip24$ltc_hcv_referral_uc_pharmacy_telehealth___1 <- ''
eip24$ltc_hcv_referral_uc_pharmacy_telehealth___2 <- ''
eip24$ltc_hcv_referral_uc_pharmacy_telehealth___3 <- ''
eip24$ltc_coordinator_per_case___2 <- ''
eip24$ltc_coordinator_per_case___12 <- ''
eip24$ltc_coordinator_per_case___61 <- ''
eip24$ltc_coordinator_per_case___54 <- ''
eip24$ltc_coordinator_per_case___24 <- ''
eip24$ltc_coordinator_per_case___64 <- ''
eip24$ltc_coordinator_per_case___28 <- ''
eip24$ltc_coordinator_per_case___63 <- ''
eip24$ltc_coordinator_per_case___49 <- ''
eip24$ltc_coordinator_per_case___69 <- ''
eip24$ltc_coordinator_per_case___30 <- ''


# Removing 2023 variables that are not needed/not in 2024 dataset
eip23 <- select(eip23, -contact_by1, -contact_by10, -contact_by11, -contact_by12, -contact_by13, -contact_by14, -contact_by15, -contact_by16,
                -contact_by17, -contact_by18, -contact_by19, -contact_by2, -contact_by20, -contact_by21, -contact_by22, -contact_by23, -contact_by24,
                -contact_by25, -contact_by26, -contact_by27, -contact_by28, -contact_by29, -contact_by3, -contact_by30, -contact_by31, -contact_by32,
                -contact_by33, -contact_by34, -contact_by35, -contact_by36, -contact_by37, -contact_by38, -contact_by39, -contact_by4, -contact_by40,
                -contact_by41, -contact_by42, -contact_by43, -contact_by44, -contact_by45, -contact_by46, -contact_by47, -contact_by48, -contact_by49,
                -contact_by5, -contact_by50, -contact_by6, -contact_by7, -contact_by8, -contact_by9, -contact_purpose1, -contact_purpose10,
                -contact_purpose11, -contact_purpose12, -contact_purpose13, -contact_purpose14, -contact_purpose15, -contact_purpose16,
                -contact_purpose17, -contact_purpose18, -contact_purpose19, -contact_purpose2, -contact_purpose20, -contact_purpose21,
                -contact_purpose22, -contact_purpose23, -contact_purpose24, -contact_purpose25, -contact_purpose26, -contact_purpose27,
                -contact_purpose28, -contact_purpose29, -contact_purpose3, -contact_purpose30, -contact_purpose31, -contact_purpose32,
                -contact_purpose33, -contact_purpose34, -contact_purpose35, -contact_purpose36, -contact_purpose37, -contact_purpose38,
                -contact_purpose39, -contact_purpose4, -contact_purpose40, -contact_purpose41, -contact_purpose42, -contact_purpose43,
                -contact_purpose44, -contact_purpose45, -contact_purpose46, -contact_purpose47, -contact_purpose48, -contact_purpose49,
                -contact_purpose5, -contact_purpose50, -contact_purpose6, -contact_purpose7, -contact_purpose8, -contact_purpose9,
                -ltc_service1___7, -ltc_service10___7, -ltc_service11___7, -ltc_service12___7, -ltc_service13___7, -ltc_service14___7,
                -ltc_service15___7, -ltc_service16___7, -ltc_service17___7, -ltc_service18___7, -ltc_service19___7, -ltc_service2___7,
                -ltc_service20___7, -ltc_service21___7, -ltc_service22___7, -ltc_service23___7, -ltc_service24___7, -ltc_service25___7,
                -ltc_service26___7, -ltc_service27___7, -ltc_service28___7, -ltc_service29___7, -ltc_service3___7, -ltc_service30___7,
                -ltc_service31___7, -ltc_service32___7, -ltc_service33___7, -ltc_service34___7, -ltc_service35___7, -ltc_service36___7,
                -ltc_service37___7, -ltc_service38___7, -ltc_service39___7, -ltc_service4___7, -ltc_service40___7, -ltc_service41___7,
                -ltc_service42___7, -ltc_service43___7, -ltc_service44___7, -ltc_service45___7, -ltc_service46___7, -ltc_service47___7,
                -ltc_service48___7, -ltc_service49___7, -ltc_service5___7, -ltc_service50___7, -ltc_service6___7, -ltc_service7___7, -ltc_service8___7,
                -ltc_service9___7, -sex_selfdefined_risks, -any_drug_branch_calc, -any_drug3mo_branch_calc,
                -peer_navigator_id___24, -aspire_attend_intake_rsn___1, -aspire_attend_intake_rsn___9,
                -aspire_attend_intake_rsn___7, -aspire_attend_intake_rsn___2, -aspire_attend_intake_rsn___3,
                -aspire_attend_intake_rsn___8, -aspire_attend_intake_rsn___10, -aspire_attend_intake_rsn___6,
                -aspire_attend_intake_rsn___11, -aspire_attend_intake_rsn___4, -aspire_attend_intake_rsn___5,
                -aspire_attend_intake_rsn___16, -aspire_attend_intake_rsn___12, -aspire_attend_intake_rsn___13,
                -aspire_attend_intake_rsn___14, -aspire_attend_intake_rsn___15, -aspire_attend_intake_rsn___88,
                -aspire_attend_intake_rsn___0, -aspire_attend_intake_rsn_other, -ltc_sti_referral_hotline_date,
                -ltc_hcv_linkage_success___1, -ltc_hcv_linkage_success___2, -ltc_hcv_med_complete_date,
                -duba_ltc_open_calc, -fouch_ltc_open_calc)
setdiff(names(eip23), names(eip24))
setdiff(names(eip24), names(eip23))
dim(eip23)
dim(eip24)

eip <- rbind(eip23, eip24)
dim(eip)

```

``` {r Patient Information, include=FALSE}

# Formatting variables

summary(eip$enc_date)
eip$enc_date <- as.Date(eip$enc_date, format='%m/%d/%Y')
summary(eip$enc_date)

summary(eip$dob)
eip$dob <- as.Date(eip$dob, format='%m/%d/%Y')
summary(eip$dob)


table(eip$race___1)
White <- eip[which(eip$race___1 == '1'), ]
dim(White)
White <- select(White, record_id)
White$White <- 1
table(White$White)
White <- distinct(White)
dim(White)
head(White)

table(eip$race___2)
Black <- eip[which(eip$race___2 == '1'), ]
dim(Black)
Black <- select(Black, record_id)
Black$Black <- 1
table(Black$Black)
Black <- distinct(Black)
dim(Black)
head(Black)

table(eip$race___3)
Asian <- eip[which(eip$race___3 == '1'), ]
dim(Asian)
Asian <- select(Asian, record_id)
Asian$Asian <- 1
table(Asian$Asian)
Asian <- distinct(Asian)
dim(Asian)
head(Asian)

table(eip$race___4)
AmIn <- eip[which(eip$race___4 == '1'), ]
dim(AmIn)
AmIn <- select(AmIn, record_id)
AmIn$AmIn <- 1
table(AmIn$AmIn)
AmIn <- distinct(AmIn)
dim(AmIn)
head(AmIn)

table(eip$race___5)
RaceOther <- eip[which(eip$race___5 == '1'), ]
dim(RaceOther)
RaceOther <- select(RaceOther, record_id)
RaceOther$RaceOther <- 1
table(RaceOther$RaceOther)
RaceOther <- distinct(RaceOther)
dim(RaceOther)
head(RaceOther)

table(eip$race___6)
RaceUnk <- eip[which(eip$race___6 == '1'), ]
dim(RaceUnk)
RaceUnk <- select(RaceUnk, record_id)
RaceUnk$RaceUnk <- 1
table(RaceUnk$RaceUnk)
RaceUnk <- distinct(RaceUnk)
dim(RaceUnk)
head(RaceUnk)

table(eip$ethnicity)
RaceHisp <- eip[which(eip$ethnicity == 1), ]
dim(RaceHisp)
RaceHisp <- select(RaceHisp, record_id)
RaceHisp$RaceHisp <- 1
table(RaceHisp$RaceHisp)
RaceHisp <- distinct(RaceHisp)
dim(RaceHisp)
head(RaceHisp)


race <- select(eip, record_id)
race <- distinct(race)
dim(race)


dim(race)
race <- merge(race, White, by = 'record_id', all.x = T)
race <- merge(race, Black, by = 'record_id', all.x = T)
race <- merge(race, Asian, by = 'record_id', all.x = T)
race <- merge(race, AmIn, by = 'record_id', all.x = T)
race <- merge(race, RaceOther, by = 'record_id', all.x = T)
race <- merge(race, RaceUnk, by = 'record_id', all.x = T)
race <- merge(race, RaceHisp, by = 'record_id', all.x = T)
dim(race)
head(race)

race$White[is.na(race$White)] <- 0
race$Black[is.na(race$Black)] <- 0
race$Asian[is.na(race$Asian)] <- 0
race$AmIn[is.na(race$AmIn)] <- 0
race$RaceOther[is.na(race$RaceOther)] <- 0
race$RaceUnk[is.na(race$RaceUnk)] <- 0
race$RaceHisp[is.na(race$RaceHisp)] <- 0

race$RaceNumber <- race$White + race$Black + race$Asian + race$AmIn + race$RaceOther + race$RaceUnk + race$RaceHisp
table(race$RaceNumber)
head(race)

race$race[race$RaceNumber == 1 & race$Black == 1] <- 'Black/African American'
race$race[race$RaceNumber == 1 & race$White == 1] <- 'White'
race$race[race$RaceNumber == 1 & race$Asian == 1] <- 'Asian/Pacific Islander'
race$race[race$RaceNumber == 1 & race$AmIn == 1] <- 'American Indian/Alaska native'
race$race[race$RaceNumber == 1 & race$RaceOther == 1] <- 'Other'
race$race[(race$RaceNumber == 1 & race$RaceHisp == 1) |
            (race$RaceNumber > 1 & race$RaceHisp == 1)] <- 'Hispanic/Latinx'
race$race[race$RaceNumber > 1 & race$RaceHisp != 1] <- 'Biracial/Multiracial'
race$race[race$RaceNumber == 0 | is.na(race$RaceNumber) | race$RaceUnk == 1] <- 'Unknown'
table(race$race)

dim(eip)
dim(race)
eip <- merge(eip, race, by = 'record_id', all.x = T)
dim(eip)
table(eip$race)




table(eip$sex_raised)
eip$sex[eip$sex_raised == 1] <- 'Male'
eip$sex[eip$sex_raised == 2] <- 'Female'
eip$sex[eip$sex_raised == 3 | is.na(eip$sex_raised) | eip$sex_raised == ''] <- 'Unknown/Unassigned'
table(eip$sex)



table(eip$sex_raised, eip$sex_selfdefined)
eip$gender[eip$sex_raised == 1 & eip$sex_selfdefined == 1] <- 'Male'
eip$gender[eip$sex_raised == 2 & eip$sex_selfdefined == 2] <- 'Female'
eip$gender[(eip$sex_raised == 1 & eip$sex_selfdefined == 2) |
             (eip$sex_raised == 2 & eip$sex_selfdefined == 1) |
             (eip$sex_raised == 1 & eip$sex_selfdefined == 3) |
             (eip$sex_raised == 2 & eip$sex_selfdefined == 3)] <- 'Transgender/Nonbinary'
eip$gender[(eip$sex_raised == 3 & eip$sex_selfdefined == 3) |
             is.na(eip$sex_raised) | is.na(eip$sex_selfdefined)] <- 'Unknown'
table(eip$gender)


table(eip$insurance)
eip$insurance[eip$insurance == 1] <- 'None'
eip$insurance[eip$insurance == 2] <- 'UC Health (Levy)'
eip$insurance[eip$insurance == 3] <- 'Medicaid'
eip$insurance[eip$insurance == 4] <- 'Medicare'
eip$insurance[eip$insurance == 5] <- 'Military/VA'
eip$insurance[eip$insurance == 6] <- 'Private'
eip$insurance[eip$insurance == 7] <- 'Dual Medicaid/Medicare'
eip$insurance[is.na(eip$insurance)] <- 'Unknown'
table(eip$insurance)



# Populations of Interest
### WOC, Youth (18-29), MSM, IDU, HRHS, PLWHA

table(eip$race, eip$gender)
eip$WOC[(eip$race != 'White' & eip$race != 'Unknown') & eip$gender == 'Female'] <- 1
table(eip$WOC)


table(eip$age)
eip$Youth[eip$age >= 13 & eip$age <= 29] <- 1
table(eip$Youth)


eip$MSM[eip$gender == 'Male' & ((eip$sex_orientation == '2' | eip$sex_orientation == '4') |
                                  (eip$sex_w_man___1 == '1' | eip$sex_w_man___2 == '1' |
                                     eip$sex_w_man___3 == '1') |
                                  (eip$sex_w_ftm___1 == '1' | eip$sex_w_ftm___2 == '1' |
                                     eip$sex_w_ftm___3 == '1') |
                                  (eip$sex_msm___1 == '1' | eip$sex_msm___2 == '1' |
                                     eip$sex_msm___3 == '1') |
                                  (eip$hiv_dx_risks___2 == '1'))] <- 1
table(eip$MSM)


eip$IDU[eip$idu_calc == 1 | eip$hiv_dx_risks___3 == '1'] <- 1
table(eip$IDU)


# For HRHS, all sexual behavior is within the previous 12 months
### Heterosexual males that have unprotected sex with women
### Heterosexual women that have unprotected sex with men
### Heterosexual women that have sex with MSM
### Heterosexual men/women that have sex with IDU
### Heterosexual men/women that have sex with HIV+ partner
### Heterosexual men/women that exchange money/drugs for sex
### Heterosexual men/women that have sex with STD+ partner
### Heterosexual men/women that have more than 3 partners

eip$Hetero[(eip$gender == 'Male' & (eip$sex_w_woman___1 == '1' |
                                      eip$sex_w_woman___2 == '1' |
                                      eip$sex_w_woman___3 == '1' |
                                      eip$sex_orientation == '1')) |
             (eip$gender == 'Female' & (eip$sex_w_man___1 == '1' |
                                          eip$sex_w_man___2 == '1' |
                                          eip$sex_w_man___3 == '1' |
                                          eip$sex_orientation == '1'))] <- 1
table(eip$Hetero)


eip$HRHS[((eip$Hetero == 1) & ((((eip$sex_w_woman___6 == '1' | eip$sex_w_woman___7 == '1') |
                                   (is.na(eip$sex_w_woman___6) & is.na(eip$sex_w_woman___7) &
                                      is.na(eip$sex_w_woman___8)))) | (((eip$sex_w_man___6 == '1' |
                                                                           eip$sex_w_man___7 == '1') |
                                                                          (is.na(eip$sex_w_man___6) &
                                                                             is.na(eip$sex_w_man___7) &
                                                                             is.na(eip$sex_w_man___8)))) |
                                 (eip$sex_msm___1 == '1' | eip$sex_msm___2 == '1' | eip$sex_msm___3 == '1') |
                                 (eip$sex_idu___1 == '1' | eip$sex_idu___2 == '1' | eip$sex_idu___3 == '1') |
                                 (eip$sex_hiv_pos___1 == '1' | eip$sex_hiv_pos___2 == '1' |
                                    eip$sex_hiv_pos___3 == '1') | (eip$sex_receivemoney___1 == '1' |
                                                                     eip$sex_receivemoney___2 == '1' |
                                                                     eip$sex_receivemoney___3 == '1' |
                                                                     eip$sex_receivedrugs___1 == '1' |
                                                                     eip$sex_receivedrugs___2 == '1' |
                                                                     eip$sex_receivedrugs___3 == '1' |
                                                                     eip$sex_paymoney___1 == '1' |
                                                                     eip$sex_paymoney___2 == '1' |
                                                                     eip$sex_paymoney___3 == '1' |
                                                                     eip$sex_paydrugs___1 == '1' |
                                                                     eip$sex_paydrugs___2 == '1' |
                                                                     eip$sex_paydrugs___3 == '1')  |
                                 (eip$sex_sti_pos___1 == '1' | eip$sex_sti_pos___2 == '1' |
                                    eip$sex_sti_pos___3 == '1') | (eip$sex_partners_past_year >= 3))) |
           (eip$hiv_dx_risks___1 == '1')] <- 1
table(eip$HRHS)




# Appalachian

eip$appalachian_pt[eip$address_zip_code == 43006 | eip$address_zip_code == 43056 |
                     eip$address_zip_code == 43076 | eip$address_zip_code == 43101 |
                     eip$address_zip_code == 43102 | eip$address_zip_code == 43107 |
                     eip$address_zip_code == 43111 | eip$address_zip_code == 43115 |
                     eip$address_zip_code == 43127 | eip$address_zip_code == 43135 |
                     eip$address_zip_code == 43138 | eip$address_zip_code == 43144 |
                     eip$address_zip_code == 43148 | eip$address_zip_code == 43149 |
                     eip$address_zip_code == 43150 | eip$address_zip_code == 43152 |
                     eip$address_zip_code == 43155 | eip$address_zip_code == 43158 |
                     eip$address_zip_code == 43160 | eip$address_zip_code == 43164 |
                     eip$address_zip_code == 43701 | eip$address_zip_code == 43702 |
                     eip$address_zip_code == 43711 | eip$address_zip_code == 43713 |
                     eip$address_zip_code == 43716 | eip$address_zip_code == 43717 |
                     eip$address_zip_code == 43718 | eip$address_zip_code == 43719 |
                     eip$address_zip_code == 43720 | eip$address_zip_code == 43722 |
                     eip$address_zip_code == 43723 | eip$address_zip_code == 43724 |
                     eip$address_zip_code == 43725 | eip$address_zip_code == 43727 |
                     eip$address_zip_code == 43728 | eip$address_zip_code == 43730 |
                     eip$address_zip_code == 43731 | eip$address_zip_code == 43732 |
                     eip$address_zip_code == 43733 | eip$address_zip_code == 43734 |
                     eip$address_zip_code == 43735 | eip$address_zip_code == 43736 |
                     eip$address_zip_code == 43738 | eip$address_zip_code == 43739 |
                     eip$address_zip_code == 43746 | eip$address_zip_code == 43747 |
                     eip$address_zip_code == 43748 | eip$address_zip_code == 43749 |
                     eip$address_zip_code == 43750 | eip$address_zip_code == 43752 |
                     eip$address_zip_code == 43754 | eip$address_zip_code == 43755 |
                     eip$address_zip_code == 43756 | eip$address_zip_code == 43757 |
                     eip$address_zip_code == 43758 | eip$address_zip_code == 43759 |
                     eip$address_zip_code == 43760 | eip$address_zip_code == 43761 |
                     eip$address_zip_code == 43762 | eip$address_zip_code == 43764 |
                     eip$address_zip_code == 43766 | eip$address_zip_code == 43767 |
                     eip$address_zip_code == 43768 | eip$address_zip_code == 43771 |
                     eip$address_zip_code == 43772 | eip$address_zip_code == 43773 |
                     eip$address_zip_code == 43777 | eip$address_zip_code == 43778 |
                     eip$address_zip_code == 43779 | eip$address_zip_code == 43780 |
                     eip$address_zip_code == 43782 | eip$address_zip_code == 43783 |
                     eip$address_zip_code == 43786 | eip$address_zip_code == 43787 |
                     eip$address_zip_code == 43788 | eip$address_zip_code == 43791 |
                     eip$address_zip_code == 43793 | eip$address_zip_code == 43802 |
                     eip$address_zip_code == 43803 | eip$address_zip_code == 43804 |
                     eip$address_zip_code == 43805 | eip$address_zip_code == 43811 |
                     eip$address_zip_code == 43812 | eip$address_zip_code == 43821 |
                     eip$address_zip_code == 43822 | eip$address_zip_code == 43824 |
                     eip$address_zip_code == 43828 | eip$address_zip_code == 43830 |
                     eip$address_zip_code == 43832 | eip$address_zip_code == 43836 |
                     eip$address_zip_code == 43837 | eip$address_zip_code == 43840 |
                     eip$address_zip_code == 43842 | eip$address_zip_code == 43843 |
                     eip$address_zip_code == 43844 | eip$address_zip_code == 43845 |
                     eip$address_zip_code == 43901 | eip$address_zip_code == 43902 |
                     eip$address_zip_code == 43903 | eip$address_zip_code == 43905 |
                     eip$address_zip_code == 43906 | eip$address_zip_code == 43907 |
                     eip$address_zip_code == 43908 | eip$address_zip_code == 43909 |
                     eip$address_zip_code == 43910 | eip$address_zip_code == 43912 |
                     eip$address_zip_code == 43913 | eip$address_zip_code == 43914 |
                     eip$address_zip_code == 43915 | eip$address_zip_code == 43916 |
                     eip$address_zip_code == 43917 | eip$address_zip_code == 43920 |
                     eip$address_zip_code == 43925 | eip$address_zip_code == 43926 |
                     eip$address_zip_code == 43927 | eip$address_zip_code == 43928 |
                     eip$address_zip_code == 43930 | eip$address_zip_code == 43931 |
                     eip$address_zip_code == 43932 | eip$address_zip_code == 43933 |
                     eip$address_zip_code == 43934 | eip$address_zip_code == 43935 |
                     eip$address_zip_code == 43937 | eip$address_zip_code == 43938 |
                     eip$address_zip_code == 43939 | eip$address_zip_code == 43940 |
                     eip$address_zip_code == 43941 | eip$address_zip_code == 43942 |
                     eip$address_zip_code == 43943 | eip$address_zip_code == 43944 |
                     eip$address_zip_code == 43945 | eip$address_zip_code == 43946 |
                     eip$address_zip_code == 43947 | eip$address_zip_code == 43948 |
                     eip$address_zip_code == 43950 | eip$address_zip_code == 43951 |
                     eip$address_zip_code == 43952 | eip$address_zip_code == 43953 |
                     eip$address_zip_code == 43961 | eip$address_zip_code == 43962 |
                     eip$address_zip_code == 43963 | eip$address_zip_code == 43964 |
                     eip$address_zip_code == 43967 | eip$address_zip_code == 43968 |
                     eip$address_zip_code == 43970 | eip$address_zip_code == 43971 |
                     eip$address_zip_code == 43972 | eip$address_zip_code == 43973 |
                     eip$address_zip_code == 43974 | eip$address_zip_code == 43976 |
                     eip$address_zip_code == 43977 | eip$address_zip_code == 43981 |
                     eip$address_zip_code == 43983 | eip$address_zip_code == 43984 |
                     eip$address_zip_code == 43985 | eip$address_zip_code == 43986 |
                     eip$address_zip_code == 43988 | eip$address_zip_code == 44003 |
                     eip$address_zip_code == 44004 | eip$address_zip_code == 44005 |
                     eip$address_zip_code == 44010 | eip$address_zip_code == 44030 |
                     eip$address_zip_code == 44032 | eip$address_zip_code == 44041 |
                     eip$address_zip_code == 44046 | eip$address_zip_code == 44047 |
                     eip$address_zip_code == 44048 | eip$address_zip_code == 44057 |
                     eip$address_zip_code == 44062 | eip$address_zip_code == 44064 |
                     eip$address_zip_code == 44068 | eip$address_zip_code == 44076 |
                     eip$address_zip_code == 44082 | eip$address_zip_code == 44084 |
                     eip$address_zip_code == 44085 | eip$address_zip_code == 44086 |
                     eip$address_zip_code == 44088 | eip$address_zip_code == 44093 |
                     eip$address_zip_code == 44099 | eip$address_zip_code == 44231 |
                     eip$address_zip_code == 44288 | eip$address_zip_code == 44401 |
                     eip$address_zip_code == 44402 | eip$address_zip_code == 44403 |
                     eip$address_zip_code == 44404 | eip$address_zip_code == 44405 |
                     eip$address_zip_code == 44406 | eip$address_zip_code == 44408 |
                     eip$address_zip_code == 44410 | eip$address_zip_code == 44411 |
                     eip$address_zip_code == 44412 | eip$address_zip_code == 44413 |
                     eip$address_zip_code == 44415 | eip$address_zip_code == 44416 |
                     eip$address_zip_code == 44417 | eip$address_zip_code == 44418 |
                     eip$address_zip_code == 44420 | eip$address_zip_code == 44422 |
                     eip$address_zip_code == 44423 | eip$address_zip_code == 44424 |
                     eip$address_zip_code == 44425 | eip$address_zip_code == 44427 |
                     eip$address_zip_code == 44428 | eip$address_zip_code == 44429 |
                     eip$address_zip_code == 44430 | eip$address_zip_code == 44431 |
                     eip$address_zip_code == 44432 | eip$address_zip_code == 44436 |
                     eip$address_zip_code == 44437 | eip$address_zip_code == 44438 |
                     eip$address_zip_code == 44439 | eip$address_zip_code == 44440 |
                     eip$address_zip_code == 44441 | eip$address_zip_code == 44442 |
                     eip$address_zip_code == 44443 | eip$address_zip_code == 44444 |
                     eip$address_zip_code == 44445 | eip$address_zip_code == 44446 |
                     eip$address_zip_code == 44449 | eip$address_zip_code == 44450 |
                     eip$address_zip_code == 44451 | eip$address_zip_code == 44452 |
                     eip$address_zip_code == 44453 | eip$address_zip_code == 44454 |
                     eip$address_zip_code == 44455 | eip$address_zip_code == 44460 |
                     eip$address_zip_code == 44470 | eip$address_zip_code == 44471 |
                     eip$address_zip_code == 44473 | eip$address_zip_code == 44481 |
                     eip$address_zip_code == 44482 | eip$address_zip_code == 44483 |
                     eip$address_zip_code == 44484 | eip$address_zip_code == 44485 |
                     eip$address_zip_code == 44486 | eip$address_zip_code == 44490 |
                     eip$address_zip_code == 44491 | eip$address_zip_code == 44492 |
                     eip$address_zip_code == 44493 | eip$address_zip_code == 44501 |
                     eip$address_zip_code == 44502 | eip$address_zip_code == 44503 |
                     eip$address_zip_code == 44504 | eip$address_zip_code == 44505 |
                     eip$address_zip_code == 44506 | eip$address_zip_code == 44507 |
                     eip$address_zip_code == 44509 | eip$address_zip_code == 44510 |
                     eip$address_zip_code == 44511 | eip$address_zip_code == 44512 |
                     eip$address_zip_code == 44513 | eip$address_zip_code == 44514 |
                     eip$address_zip_code == 44515 | eip$address_zip_code == 44555 |
                     eip$address_zip_code == 44601 | eip$address_zip_code == 44607 |
                     eip$address_zip_code == 44608 | eip$address_zip_code == 44609 |
                     eip$address_zip_code == 44610 | eip$address_zip_code == 44611 |
                     eip$address_zip_code == 44612 | eip$address_zip_code == 44615 |
                     eip$address_zip_code == 44617 | eip$address_zip_code == 44619 |
                     eip$address_zip_code == 44620 | eip$address_zip_code == 44621 |
                     eip$address_zip_code == 44622 | eip$address_zip_code == 44624 |
                     eip$address_zip_code == 44625 | eip$address_zip_code == 44626 |
                     eip$address_zip_code == 44627 | eip$address_zip_code == 44628 |
                     eip$address_zip_code == 44629 | eip$address_zip_code == 44633 |
                     eip$address_zip_code == 44634 | eip$address_zip_code == 44637 |
                     eip$address_zip_code == 44638 | eip$address_zip_code == 44639 |
                     eip$address_zip_code == 44643 | eip$address_zip_code == 44644 |
                     eip$address_zip_code == 44651 | eip$address_zip_code == 44653 |
                     eip$address_zip_code == 44654 | eip$address_zip_code == 44656 |
                     eip$address_zip_code == 44657 | eip$address_zip_code == 44660 |
                     eip$address_zip_code == 44661 | eip$address_zip_code == 44663 |
                     eip$address_zip_code == 44665 | eip$address_zip_code == 44671 |
                     eip$address_zip_code == 44672 | eip$address_zip_code == 44675 |
                     eip$address_zip_code == 44676 | eip$address_zip_code == 44678 |
                     eip$address_zip_code == 44679 | eip$address_zip_code == 44680 |
                     eip$address_zip_code == 44681 | eip$address_zip_code == 44682 |
                     eip$address_zip_code == 44683 | eip$address_zip_code == 44687 |
                     eip$address_zip_code == 44688 | eip$address_zip_code == 44689 |
                     eip$address_zip_code == 44690 | eip$address_zip_code == 44693 |
                     eip$address_zip_code == 44695 | eip$address_zip_code == 44697 |
                     eip$address_zip_code == 44699 | eip$address_zip_code == 44730 |
                     eip$address_zip_code == 44842 | eip$address_zip_code == 45101 |
                     eip$address_zip_code == 45102 | eip$address_zip_code == 45103 |
                     eip$address_zip_code == 45105 | eip$address_zip_code == 45106 |
                     eip$address_zip_code == 45107 | eip$address_zip_code == 45112 |
                     eip$address_zip_code == 45115 | eip$address_zip_code == 45118 |
                     eip$address_zip_code == 45119 | eip$address_zip_code == 45120 |
                     eip$address_zip_code == 45121 | eip$address_zip_code == 45122 |
                     eip$address_zip_code == 45123 | eip$address_zip_code == 45130 |
                     eip$address_zip_code == 45131 | eip$address_zip_code == 45132 |
                     eip$address_zip_code == 45133 | eip$address_zip_code == 45135 |
                     eip$address_zip_code == 45140 | eip$address_zip_code == 45142 |
                     eip$address_zip_code == 45144 | eip$address_zip_code == 45147 |
                     eip$address_zip_code == 45148 | eip$address_zip_code == 45150 |
                     eip$address_zip_code == 45153 | eip$address_zip_code == 45154 |
                     eip$address_zip_code == 45155 | eip$address_zip_code == 45156 |
                     eip$address_zip_code == 45157 | eip$address_zip_code == 45158 |
                     eip$address_zip_code == 45159 | eip$address_zip_code == 45160 |
                     eip$address_zip_code == 45162 | eip$address_zip_code == 45167 |
                     eip$address_zip_code == 45168 | eip$address_zip_code == 45171 |
                     eip$address_zip_code == 45172 | eip$address_zip_code == 45176 |
                     eip$address_zip_code == 45244 | eip$address_zip_code == 45245 |
                     eip$address_zip_code == 45255 | eip$address_zip_code == 45601 |
                     eip$address_zip_code == 45612 | eip$address_zip_code == 45613 |
                     eip$address_zip_code == 45614 | eip$address_zip_code == 45616 |
                     eip$address_zip_code == 45617 | eip$address_zip_code == 45618 |
                     eip$address_zip_code == 45619 | eip$address_zip_code == 45620 |
                     eip$address_zip_code == 45621 | eip$address_zip_code == 45622 |
                     eip$address_zip_code == 45623 | eip$address_zip_code == 45624 |
                     eip$address_zip_code == 45628 | eip$address_zip_code == 45629 |
                     eip$address_zip_code == 45630 | eip$address_zip_code == 45631 |
                     eip$address_zip_code == 45633 | eip$address_zip_code == 45634 |
                     eip$address_zip_code == 45636 | eip$address_zip_code == 45638 |
                     eip$address_zip_code == 45640 | eip$address_zip_code == 45642 |
                     eip$address_zip_code == 45643 | eip$address_zip_code == 45644 |
                     eip$address_zip_code == 45645 | eip$address_zip_code == 45646 |
                     eip$address_zip_code == 45647 | eip$address_zip_code == 45648 |
                     eip$address_zip_code == 45650 | eip$address_zip_code == 45651 |
                     eip$address_zip_code == 45652 | eip$address_zip_code == 45653 |
                     eip$address_zip_code == 45654 | eip$address_zip_code == 45656 |
                     eip$address_zip_code == 45657 | eip$address_zip_code == 45658 |
                     eip$address_zip_code == 45659 | eip$address_zip_code == 45660 |
                     eip$address_zip_code == 45661 | eip$address_zip_code == 45662 |
                     eip$address_zip_code == 45663 | eip$address_zip_code == 45669 |
                     eip$address_zip_code == 45671 | eip$address_zip_code == 45672 |
                     eip$address_zip_code == 45673 | eip$address_zip_code == 45674 |
                     eip$address_zip_code == 45675 | eip$address_zip_code == 45677 |
                     eip$address_zip_code == 45678 | eip$address_zip_code == 45679 |
                     eip$address_zip_code == 45680 | eip$address_zip_code == 45681 |
                     eip$address_zip_code == 45682 | eip$address_zip_code == 45683 |
                     eip$address_zip_code == 45684 | eip$address_zip_code == 45685 |
                     eip$address_zip_code == 45686 | eip$address_zip_code == 45687 |
                     eip$address_zip_code == 45688 | eip$address_zip_code == 45690 |
                     eip$address_zip_code == 45692 | eip$address_zip_code == 45693 |
                     eip$address_zip_code == 45694 | eip$address_zip_code == 45695 |
                     eip$address_zip_code == 45696 | eip$address_zip_code == 45697 |
                     eip$address_zip_code == 45698 | eip$address_zip_code == 45699 |
                     eip$address_zip_code == 45701 | eip$address_zip_code == 45710 |
                     eip$address_zip_code == 45711 | eip$address_zip_code == 45712 |
                     eip$address_zip_code == 45713 | eip$address_zip_code == 45714 |
                     eip$address_zip_code == 45715 | eip$address_zip_code == 45716 |
                     eip$address_zip_code == 45717 | eip$address_zip_code == 45719 |
                     eip$address_zip_code == 45720 | eip$address_zip_code == 45721 |
                     eip$address_zip_code == 45723 | eip$address_zip_code == 45724 |
                     eip$address_zip_code == 45727 | eip$address_zip_code == 45729 |
                     eip$address_zip_code == 45732 | eip$address_zip_code == 45734 |
                     eip$address_zip_code == 45735 | eip$address_zip_code == 45739 |
                     eip$address_zip_code == 45740 | eip$address_zip_code == 45741 |
                     eip$address_zip_code == 45742 | eip$address_zip_code == 45743 |
                     eip$address_zip_code == 45744 | eip$address_zip_code == 45745 |
                     eip$address_zip_code == 45746 | eip$address_zip_code == 45750 |
                     eip$address_zip_code == 45760 | eip$address_zip_code == 45761 |
                     eip$address_zip_code == 45764 | eip$address_zip_code == 45766 |
                     eip$address_zip_code == 45767 | eip$address_zip_code == 45768 |
                     eip$address_zip_code == 45769 | eip$address_zip_code == 45770 |
                     eip$address_zip_code == 45771 | eip$address_zip_code == 45772 |
                     eip$address_zip_code == 45773 | eip$address_zip_code == 45775 |
                     eip$address_zip_code == 45776 | eip$address_zip_code == 45777 |
                     eip$address_zip_code == 45778 | eip$address_zip_code == 45779 |
                     eip$address_zip_code == 45780 | eip$address_zip_code == 45782 |
                     eip$address_zip_code == 45783 | eip$address_zip_code == 45784 |
                     eip$address_zip_code == 45786 | eip$address_zip_code == 45787 |
                     eip$address_zip_code == 45788 | eip$address_zip_code == 45789 |
                     (eip$appalachian == 1 | eip$appalachian_family == 1)] <- 1
table(eip$appalachian_pt)



# EIP unique patients
dim(eip)
eip_pts <- select(eip, record_id)
dim(eip_pts)
eip_pts <- distinct(eip_pts)
dim(eip_pts)

eip_patients <- nrow(eip_pts)
eip_patients



# PLWHA
eip$plwha[(eip$history_hiv_test_result == 1 |
             eip$reason_for_offer_category_hiv_test == 7 |
             eip$reason_for_offer_category_hiv_test == 8 |
             eip$offer_outcome_declined_hiv___21 == 1 |
             eip$offer_outcome_declined_hiv_2___21 == 1 |
             eip$offer_outcome_declined_hiv_3___21 == 1 |
             eip$final_test_status_hiv == 1 |
             eip$diagnosis_hiv == 1 |
             eip$diagnosis_hiv == 2)] <- 1
table(eip$plwha)


table(eip$plwha)
plwha <- eip[which(eip$plwha == 1), ]
dim(plwha)
plwha <- nrow(plwha)
plwha



# Formatting contact note dates
eip$followup_date1 <- as.Date(eip$followup_date1, format = '%m/%d/%Y')
eip$followup_date2 <- as.Date(eip$followup_date2, format = '%m/%d/%Y')
eip$followup_date3 <- as.Date(eip$followup_date3, format = '%m/%d/%Y')
eip$followup_date4 <- as.Date(eip$followup_date4, format = '%m/%d/%Y')
eip$followup_date5 <- as.Date(eip$followup_date5, format = '%m/%d/%Y')
eip$followup_date6 <- as.Date(eip$followup_date6, format = '%m/%d/%Y')
eip$followup_date7 <- as.Date(eip$followup_date7, format = '%m/%d/%Y')
eip$followup_date8 <- as.Date(eip$followup_date8, format = '%m/%d/%Y')
eip$followup_date9 <- as.Date(eip$followup_date9, format = '%m/%d/%Y')
eip$followup_date10 <- as.Date(eip$followup_date10, format = '%m/%d/%Y')
eip$followup_date11 <- as.Date(eip$followup_date11, format = '%m/%d/%Y')
eip$followup_date12 <- as.Date(eip$followup_date12, format = '%m/%d/%Y')
eip$followup_date13 <- as.Date(eip$followup_date13, format = '%m/%d/%Y')
eip$followup_date14 <- as.Date(eip$followup_date14, format = '%m/%d/%Y')
eip$followup_date15 <- as.Date(eip$followup_date15, format = '%m/%d/%Y')
eip$followup_date16 <- as.Date(eip$followup_date16, format = '%m/%d/%Y')
eip$followup_date17 <- as.Date(eip$followup_date17, format = '%m/%d/%Y')
eip$followup_date18 <- as.Date(eip$followup_date18, format = '%m/%d/%Y')
eip$followup_date19 <- as.Date(eip$followup_date19, format = '%m/%d/%Y')
eip$followup_date20 <- as.Date(eip$followup_date20, format = '%m/%d/%Y')
eip$followup_date21 <- as.Date(eip$followup_date21, format = '%m/%d/%Y')
eip$followup_date22 <- as.Date(eip$followup_date22, format = '%m/%d/%Y')
eip$followup_date23 <- as.Date(eip$followup_date23, format = '%m/%d/%Y')
eip$followup_date24 <- as.Date(eip$followup_date24, format = '%m/%d/%Y')
eip$followup_date25 <- as.Date(eip$followup_date25, format = '%m/%d/%Y')
eip$followup_date26 <- as.Date(eip$followup_date26, format = '%m/%d/%Y')
eip$followup_date27 <- as.Date(eip$followup_date27, format = '%m/%d/%Y')
eip$followup_date28 <- as.Date(eip$followup_date28, format = '%m/%d/%Y')
eip$followup_date29 <- as.Date(eip$followup_date29, format = '%m/%d/%Y')
eip$followup_date30 <- as.Date(eip$followup_date30, format = '%m/%d/%Y')
eip$followup_date31 <- as.Date(eip$followup_date31, format = '%m/%d/%Y')
eip$followup_date32 <- as.Date(eip$followup_date32, format = '%m/%d/%Y')
eip$followup_date33 <- as.Date(eip$followup_date33, format = '%m/%d/%Y')
eip$followup_date34 <- as.Date(eip$followup_date34, format = '%m/%d/%Y')
eip$followup_date35 <- as.Date(eip$followup_date35, format = '%m/%d/%Y')
eip$followup_date36 <- as.Date(eip$followup_date36, format = '%m/%d/%Y')
eip$followup_date37 <- as.Date(eip$followup_date37, format = '%m/%d/%Y')
eip$followup_date38 <- as.Date(eip$followup_date38, format = '%m/%d/%Y')
eip$followup_date39 <- as.Date(eip$followup_date39, format = '%m/%d/%Y')
eip$followup_date40 <- as.Date(eip$followup_date40, format = '%m/%d/%Y')
eip$followup_date41 <- as.Date(eip$followup_date41, format = '%m/%d/%Y')
eip$followup_date42 <- as.Date(eip$followup_date42, format = '%m/%d/%Y')
eip$followup_date43 <- as.Date(eip$followup_date43, format = '%m/%d/%Y')
eip$followup_date44 <- as.Date(eip$followup_date44, format = '%m/%d/%Y')
eip$followup_date45 <- as.Date(eip$followup_date45, format = '%m/%d/%Y')
eip$followup_date46 <- as.Date(eip$followup_date46, format = '%m/%d/%Y')
eip$followup_date47 <- as.Date(eip$followup_date47, format = '%m/%d/%Y')
eip$followup_date48 <- as.Date(eip$followup_date48, format = '%m/%d/%Y')
eip$followup_date49 <- as.Date(eip$followup_date49, format = '%m/%d/%Y')
eip$followup_date50 <- as.Date(eip$followup_date50, format = '%m/%d/%Y')


# Formatting timeframe between encounter date and contact note
eip$datediff1 <- as.numeric(interval(eip$enc_date, eip$followup_date1)/ddays(1))
eip$datediff2 <- as.numeric(interval(eip$enc_date, eip$followup_date2)/ddays(1))
eip$datediff3 <- as.numeric(interval(eip$enc_date, eip$followup_date3)/ddays(1))
eip$datediff4 <- as.numeric(interval(eip$enc_date, eip$followup_date4)/ddays(1))
eip$datediff5 <- as.numeric(interval(eip$enc_date, eip$followup_date5)/ddays(1))
eip$datediff6 <- as.numeric(interval(eip$enc_date, eip$followup_date6)/ddays(1))
eip$datediff7 <- as.numeric(interval(eip$enc_date, eip$followup_date7)/ddays(1))
eip$datediff8 <- as.numeric(interval(eip$enc_date, eip$followup_date8)/ddays(1))
eip$datediff9 <- as.numeric(interval(eip$enc_date, eip$followup_date9)/ddays(1))
eip$datediff10 <- as.numeric(interval(eip$enc_date, eip$followup_date10)/ddays(1))
eip$datediff11 <- as.numeric(interval(eip$enc_date, eip$followup_date11)/ddays(1))
eip$datediff12 <- as.numeric(interval(eip$enc_date, eip$followup_date12)/ddays(1))
eip$datediff13 <- as.numeric(interval(eip$enc_date, eip$followup_date13)/ddays(1))
eip$datediff14 <- as.numeric(interval(eip$enc_date, eip$followup_date14)/ddays(1))
eip$datediff15 <- as.numeric(interval(eip$enc_date, eip$followup_date15)/ddays(1))
eip$datediff16 <- as.numeric(interval(eip$enc_date, eip$followup_date16)/ddays(1))
eip$datediff17 <- as.numeric(interval(eip$enc_date, eip$followup_date17)/ddays(1))
eip$datediff18 <- as.numeric(interval(eip$enc_date, eip$followup_date18)/ddays(1))
eip$datediff19 <- as.numeric(interval(eip$enc_date, eip$followup_date19)/ddays(1))
eip$datediff20 <- as.numeric(interval(eip$enc_date, eip$followup_date20)/ddays(1))
eip$datediff21 <- as.numeric(interval(eip$enc_date, eip$followup_date21)/ddays(1))
eip$datediff22 <- as.numeric(interval(eip$enc_date, eip$followup_date22)/ddays(1))
eip$datediff23 <- as.numeric(interval(eip$enc_date, eip$followup_date23)/ddays(1))
eip$datediff24 <- as.numeric(interval(eip$enc_date, eip$followup_date24)/ddays(1))
eip$datediff25 <- as.numeric(interval(eip$enc_date, eip$followup_date25)/ddays(1))
eip$datediff26 <- as.numeric(interval(eip$enc_date, eip$followup_date26)/ddays(1))
eip$datediff27 <- as.numeric(interval(eip$enc_date, eip$followup_date27)/ddays(1))
eip$datediff28 <- as.numeric(interval(eip$enc_date, eip$followup_date28)/ddays(1))
eip$datediff29 <- as.numeric(interval(eip$enc_date, eip$followup_date29)/ddays(1))
eip$datediff30 <- as.numeric(interval(eip$enc_date, eip$followup_date30)/ddays(1))
eip$datediff31 <- as.numeric(interval(eip$enc_date, eip$followup_date31)/ddays(1))
eip$datediff32 <- as.numeric(interval(eip$enc_date, eip$followup_date32)/ddays(1))
eip$datediff33 <- as.numeric(interval(eip$enc_date, eip$followup_date33)/ddays(1))
eip$datediff34 <- as.numeric(interval(eip$enc_date, eip$followup_date34)/ddays(1))
eip$datediff35 <- as.numeric(interval(eip$enc_date, eip$followup_date35)/ddays(1))
eip$datediff36 <- as.numeric(interval(eip$enc_date, eip$followup_date36)/ddays(1))
eip$datediff37 <- as.numeric(interval(eip$enc_date, eip$followup_date37)/ddays(1))
eip$datediff38 <- as.numeric(interval(eip$enc_date, eip$followup_date38)/ddays(1))
eip$datediff39 <- as.numeric(interval(eip$enc_date, eip$followup_date39)/ddays(1))
eip$datediff40 <- as.numeric(interval(eip$enc_date, eip$followup_date40)/ddays(1))
eip$datediff41 <- as.numeric(interval(eip$enc_date, eip$followup_date41)/ddays(1))
eip$datediff42 <- as.numeric(interval(eip$enc_date, eip$followup_date42)/ddays(1))
eip$datediff43 <- as.numeric(interval(eip$enc_date, eip$followup_date43)/ddays(1))
eip$datediff44 <- as.numeric(interval(eip$enc_date, eip$followup_date44)/ddays(1))
eip$datediff45 <- as.numeric(interval(eip$enc_date, eip$followup_date45)/ddays(1))
eip$datediff46 <- as.numeric(interval(eip$enc_date, eip$followup_date46)/ddays(1))
eip$datediff47 <- as.numeric(interval(eip$enc_date, eip$followup_date47)/ddays(1))
eip$datediff48 <- as.numeric(interval(eip$enc_date, eip$followup_date48)/ddays(1))
eip$datediff49 <- as.numeric(interval(eip$enc_date, eip$followup_date49)/ddays(1))
eip$datediff50 <- as.numeric(interval(eip$enc_date, eip$followup_date50)/ddays(1))

```

```{r MH, include=FALSE}

###############################################################################################################
#########################################  Creating Encounter Dataset  ########################################
###############################################################################################################

summary(eip$enc_date)
enc <- eip[which(eip$enc_date >= '2023-01-01' & eip$enc_date <= '2024-12-31'), ]
summary(enc$enc_date)


eip_encounters <- nrow(enc)
eip_encounters



###########################################################


# MH Linkage Data

table(enc$additional_services___1)
enc$mh_ltc[enc$additional_services___1 == 1] <- 1
table(enc$mh_ltc)

table(enc$mh_ltc)
mh_ltc <- enc[which(enc$mh_ltc == 1), ]
dim(mh_ltc)
mh_ltc <- nrow(mh_ltc)
mh_ltc



# Ineligible MH Linkage - Already Linked

table(enc$ltc_mh_declined_rsn___23)
table(enc$ltc_mh_prevented_rsn___16)
enc$mh_already_linked <- NA
enc$mh_already_linked[enc$mh_ltc == 1 &
                         (enc$ltc_mh_declined_rsn___23 == 1 |
                            enc$ltc_mh_prevented_rsn___16 == 1)] <- 1
table(enc$mh_already_linked)

table(enc$mh_already_linked)
mh_already_linked <- enc[which(enc$mh_already_linked == 1), ]
dim(mh_already_linked)
mh_already_linked <- nrow(mh_already_linked)
mh_already_linked



# Ineligible MH Linkage - Deceased

table(enc$ltc_mh_declined_rsn___35)
table(enc$ltc_mh_prevented_rsn___17)
enc$mh_deceased <- NA
enc$mh_deceased[enc$mh_ltc == 1 &
                   (enc$ltc_mh_declined_rsn___35 == 1 |
                      enc$ltc_mh_prevented_rsn___17 == 1)] <- 1
table(enc$mh_deceased)

table(enc$mh_deceased)
mh_deceased <- enc[which(enc$mh_deceased == 1), ]
dim(mh_deceased)
mh_deceased <- nrow(mh_deceased)
mh_deceased



# Ineligible MH Linkage - Incarcerated

table(enc$ltc_mh_prevented_rsn___12)
enc$mh_incarcerated <- NA
enc$mh_incarcerated[enc$mh_ltc == 1 &
                       enc$ltc_mh_prevented_rsn___12 == 1] <- 1
table(enc$mh_incarcerated)

table(enc$mh_incarcerated)
mh_incarcerated <- enc[which(enc$mh_incarcerated == 1), ]
dim(mh_incarcerated)
mh_incarcerated <- nrow(mh_incarcerated)
mh_incarcerated



# Ineligible MH Linkage - Declined Linkage Service

table(enc$ltc_mh_final_ltc_status)
enc$mh_linkage_declined <- NA
enc$mh_linkage_declined[(enc$mh_ltc == 1 &
                            enc$ltc_mh_final_ltc_status == 2) &
                           (is.na(enc$mh_already_linked) &
                              is.na(enc$mh_deceased) &
                              is.na(enc$mh_incarcerated))] <- 1
table(enc$mh_linkage_declined)

table(enc$mh_linkage_declined)
mh_linkage_declined <- enc[which(enc$mh_linkage_declined == 1), ]
dim(mh_linkage_declined)
mh_linkage_declined <- nrow(mh_linkage_declined)
mh_linkage_declined



# Ineligible MH Linkage - Linkage in Progress

table(enc$ltc_mh_prevented_rsn___18)
enc$mh_ongoing_linkage <- NA
enc$mh_ongoing_linkage[enc$mh_ltc == 1 &
                          enc$ltc_mh_prevented_rsn___18 == 1] <- 1
table(enc$mh_ongoing_linkage)

table(enc$mh_ongoing_linkage)
mh_ongoing_linkage <- enc[which(enc$mh_ongoing_linkage == 1), ]
dim(mh_ongoing_linkage)
mh_ongoing_linkage <- nrow(mh_ongoing_linkage)
mh_ongoing_linkage




# MH Ineligible Cases

enc$mh_ineligible_ltc[enc$mh_already_linked == 1 |
                         enc$mh_deceased == 1 |
                         enc$mh_incarcerated == 1 |
                         enc$mh_linkage_declined == 1 |
                         enc$mh_ongoing_linkage == 1] <- 1
table(enc$mh_ineligible_ltc)

table(enc$mh_ineligible_ltc)
mh_ineligible_ltc <- enc[which(enc$mh_ineligible_ltc == 1), ]
dim(mh_ineligible_ltc)
mh_ineligible_ltc <- nrow(mh_ineligible_ltc)
mh_ineligible_ltc

mh_ineligible_ltc_percent <- percent(mh_ineligible_ltc/mh_ltc, accuracy = 0.1)
mh_ineligible_ltc_percent

mh_already_linked_percent <- percent(mh_already_linked/mh_ineligible_ltc, accuracy = 0.1)
mh_already_linked_percent

mh_deceased_percent <- percent(mh_deceased/mh_ineligible_ltc, accuracy = 0.1)
mh_deceased_percent

mh_incarcerated_percent <- percent(mh_incarcerated/mh_ineligible_ltc, accuracy = 0.1)
mh_incarcerated_percent

mh_linkage_declined_percent <- percent(mh_linkage_declined/mh_ineligible_ltc, accuracy = 0.1)
mh_linkage_declined_percent

mh_ongoing_linkage_percent <- percent(mh_ongoing_linkage/mh_ineligible_ltc, accuracy = 0.1)
mh_ongoing_linkage_percent




# MH Eligibility to be Linked

enc$mh_eligible_ltc[enc$mh_ltc == 1 &
                       (is.na(enc$mh_already_linked) &
                          is.na(enc$mh_deceased) &
                          is.na(enc$mh_incarcerated) &
                          is.na(enc$mh_linkage_declined) &
                          is.na(enc$mh_ongoing_linkage))] <- 1
table(enc$mh_eligible_ltc)

table(enc$mh_eligible_ltc)
mh_eligible_ltc <- enc[which(enc$mh_eligible_ltc == 1), ]
dim(mh_eligible_ltc)
mh_eligible_ltc <- nrow(mh_eligible_ltc)
mh_eligible_ltc

mh_eligible_ltc_percent <- percent(mh_eligible_ltc/mh_ltc, accuracy = 0.1)
mh_eligible_ltc_percent




# MH Open/Closed Cases

table(enc$ltc_mh_open_case_calc)
enc$mh_in_progress[enc$mh_eligible_ltc == 1 &
                      enc$ltc_mh_open_case_calc == 1] <- 1
table(enc$mh_in_progress)

table(enc$mh_in_progress)
mh_in_progress <- enc[which(enc$mh_in_progress == 1), ]
dim(mh_in_progress)
mh_in_progress <- nrow(mh_in_progress)
mh_in_progress

mh_in_progress_percent <- percent(mh_in_progress/mh_eligible_ltc, accuracy = 0.1)
mh_in_progress_percent



table(enc$mh_eligible_ltc, enc$mh_in_progress)
enc$mh_closed_case[enc$mh_eligible_ltc == 1 &
                      is.na(enc$mh_in_progress)] <- 1
table(enc$mh_closed_case)

table(enc$mh_closed_case)
mh_closed_case <- enc[which(enc$mh_closed_case == 1), ]
dim(mh_closed_case)
mh_closed_case <- nrow(mh_closed_case)
mh_closed_case

mh_closed_case_percent <- percent(mh_closed_case/mh_eligible_ltc, accuracy = 0.1)
mh_closed_case_percent



table(enc$mh_in_progress)
enc$mh_ltc_days_open <- difftime(Sys.Date(), enc$enc_date, units="days")
table(enc$mh_ltc_days_open)
enc$mh_in_progress_90days[enc$mh_in_progress == 1 &
                             (enc$mh_ltc_days_open > 90)] <- 1
table(enc$mh_in_progress_90days)

table(enc$mh_in_progress_90days)
mh_in_progress_90days <- enc[which(enc$mh_in_progress_90days == 1), ]
dim(mh_in_progress_90days)
mh_in_progress_90days <- nrow(mh_in_progress_90days)
mh_in_progress_90days

mh_in_progress_90days_percent <- percent(mh_in_progress_90days/mh_in_progress, accuracy = 0.1)
mh_in_progress_90days_percent




# MH Cases Linked to Care

table(enc$mh_closed_case, enc$ltc_mh_final_ltc_status)
enc$mh_linked[enc$mh_closed_case == 1 &
                 enc$ltc_mh_final_ltc_status == 1] <- 1
table(enc$mh_linked)

table(enc$mh_linked)
mh_linked <- enc[which(enc$mh_linked == 1), ]
dim(mh_linked)
mh_linked <- nrow(mh_linked)
mh_linked

mh_linked_percent <- percent(mh_linked/mh_closed_case, accuracy = 0.1)
mh_linked_percent




enc$mh_not_linked[enc$mh_eligible_ltc == 1 & is.na(enc$mh_in_progress) & is.na(enc$mh_linked)] <- 1
table(enc$mh_not_linked)

table(enc$mh_not_linked)
mh_not_linked <- enc[which(enc$mh_not_linked == 1), ]
dim(mh_not_linked)
mh_not_linked <- nrow(mh_not_linked)
mh_not_linked

mh_not_linked_percent <- percent(mh_not_linked/mh_closed_case, accuracy = 0.1)
mh_not_linked_percent




# MH Reasons Not Linked to Care

enc$mh_not_linked_med_staff[(enc$mh_closed_case == 1 & is.na(enc$mh_linked)) &
                               (enc$ltc_mh_prevented_rsn___1 == 1 |
                                  enc$ltc_mh_prevented_rsn___2 == 1 |
                                  enc$ltc_mh_prevented_rsn___11 == 1)] <- 1
table(enc$mh_not_linked_med_staff)

table(enc$mh_not_linked_med_staff)
mh_not_linked_med_staff <- enc[which(enc$mh_not_linked_med_staff == 1), ]
dim(mh_not_linked_med_staff)
mh_not_linked_med_staff <- nrow(mh_not_linked_med_staff)
mh_not_linked_med_staff

mh_not_linked_med_staff_percent <- percent(mh_not_linked_med_staff/mh_not_linked, accuracy = 0.1)
mh_not_linked_med_staff_percent



enc$mh_not_linked_family[(enc$mh_closed_case == 1 & is.na(enc$mh_linked)) &
                            (enc$ltc_mh_prevented_rsn___3 == 1)] <- 1
table(enc$mh_not_linked_family)

table(enc$mh_not_linked_family)
mh_not_linked_family <- enc[which(enc$mh_not_linked_family == 1), ]
dim(mh_not_linked_family)
mh_not_linked_family <- nrow(mh_not_linked_family)
mh_not_linked_family

mh_not_linked_family_percent <- percent(mh_not_linked_family/mh_not_linked, accuracy = 0.1)
mh_not_linked_family_percent



enc$mh_not_linked_not_talking[(enc$mh_closed_case == 1 & is.na(enc$mh_linked)) &
                                 (enc$ltc_mh_prevented_rsn___4 == 1)] <- 1
table(enc$mh_not_linked_not_talking)

table(enc$mh_not_linked_not_talking)
mh_not_linked_not_talking <- enc[which(enc$mh_not_linked_not_talking == 1), ]
dim(mh_not_linked_not_talking)
mh_not_linked_not_talking <- nrow(mh_not_linked_not_talking)
mh_not_linked_not_talking

mh_not_linked_not_talking_percent <- percent(mh_not_linked_not_talking/mh_not_linked, accuracy = 0.1)
mh_not_linked_not_talking_percent



enc$mh_not_linked_safety[(enc$mh_closed_case == 1 & is.na(enc$mh_linked)) &
                            (enc$ltc_mh_prevented_rsn___5 == 1)] <- 1
table(enc$mh_not_linked_safety)

table(enc$mh_not_linked_safety)
mh_not_linked_safety <- enc[which(enc$mh_not_linked_safety == 1), ]
dim(mh_not_linked_safety)
mh_not_linked_safety <- nrow(mh_not_linked_safety)
mh_not_linked_safety

mh_not_linked_safety_percent <- percent(mh_not_linked_safety/mh_not_linked, accuracy = 0.1)
mh_not_linked_safety_percent



enc$mh_not_linked_medical[(enc$mh_closed_case == 1 & is.na(enc$mh_linked)) &
                             (enc$ltc_mh_prevented_rsn___6 == 1 |
                                enc$ltc_mh_prevented_rsn___8)] <- 1
table(enc$mh_not_linked_medical)

table(enc$mh_not_linked_medical)
mh_not_linked_medical <- enc[which(enc$mh_not_linked_medical == 1), ]
dim(mh_not_linked_medical)
mh_not_linked_medical <- nrow(mh_not_linked_medical)
mh_not_linked_medical

mh_not_linked_medical_percent <- percent(mh_not_linked_medical/mh_not_linked, accuracy = 0.1)
mh_not_linked_medical_percent



enc$mh_not_linked_contact[(enc$mh_closed_case == 1 & is.na(enc$mh_linked)) &
                             (enc$ltc_mh_prevented_rsn___20 == 1)] <- 1
table(enc$mh_not_linked_contact)

table(enc$mh_not_linked_contact)
mh_not_linked_contact <- enc[which(enc$mh_not_linked_contact == 1), ]
dim(mh_not_linked_contact)
mh_not_linked_contact <- nrow(mh_not_linked_contact)
mh_not_linked_contact

mh_not_linked_contact_percent <- percent(mh_not_linked_contact/mh_not_linked, accuracy = 0.1)
mh_not_linked_contact_percent



enc$mh_not_linked_language[(enc$mh_closed_case == 1 & is.na(enc$mh_linked)) &
                              (enc$ltc_mh_prevented_rsn___9 == 1)] <- 1
table(enc$mh_not_linked_language)

table(enc$mh_not_linked_language)
mh_not_linked_language <- enc[which(enc$mh_not_linked_language == 1), ]
dim(mh_not_linked_language)
mh_not_linked_language <- nrow(mh_not_linked_language)
mh_not_linked_language

mh_not_linked_language_percent <- percent(mh_not_linked_language/mh_not_linked, accuracy = 0.1)
mh_not_linked_language_percent



enc$mh_not_linked_other[(enc$mh_closed_case == 1 & is.na(enc$mh_linked)) &
                           (enc$ltc_mh_prevented_rsn___0 == 1)] <- 1
table(enc$mh_not_linked_other)

table(enc$mh_not_linked_other)
mh_not_linked_other <- enc[which(enc$mh_not_linked_other == 1), ]
dim(mh_not_linked_other)
mh_not_linked_other <- nrow(mh_not_linked_other)
mh_not_linked_other

mh_not_linked_other_percent <- percent(mh_not_linked_other/mh_not_linked, accuracy = 0.1)
mh_not_linked_other_percent



```




# MH Linkage to Care


The flowchart of the MH Linkage to Care efforts for EIP are shown below.


```{r, echo=FALSE}

grid_data <- tibble(x= 1:100, y= 1:100)

grid_data %>% 
  ggplot(aes(x, y)) +
  scale_x_continuous(minor_breaks = seq(10, 100, 10)) +
  scale_y_continuous(minor_breaks = seq(10, 100, 10)) +
  theme_linedraw() ->
  grid


grid +
  # MH Linkage Cases
  geom_rect(xmin = 0, xmax = 22, ymin = 90, ymax = 100, color = 'black',
            fill = 'mediumpurple1', size = 0.25, size = 0.25) +
  annotate('text', x = 10.5, y = 97, label = 'MH Linkage Cases', size = 2) +
  geom_rect(xmin = 0, xmax = 22, ymin = 90, ymax = 100, color = NA,
            fill = NA, size = 0.25) +
  annotate('text', x = 10.5, y = 93, label = mh_ltc, size = 2, color = 'purple4') +
  
  # Ineligible for Linkage
  geom_rect(xmin = 41, xmax = 63, ymin = 75, ymax = 85, color = 'gray',
            fill = 'white', size = 0.25) +
  annotate('text', x = 52.5, y = 82, label = 'Ineligible for Linkage', size = 2) +
  geom_rect(xmin = 41, xmax = 63, ymin = 75, ymax = 85, color = NA,
            fill = NA, size = 0.25) +
  annotate('text', x = 51.5, y = 78, label = mh_ineligible_ltc, size = 2, color = 'purple4') +
  annotate('text', x = 60, y = 78, label = mh_ineligible_ltc_percent, size = 2, color = 'magenta4') +
  
  
  # Reasons Ineligible for Linkage
  geom_rect(xmin = 83, xmax = 100, ymin = 75, ymax = 85, color = NA,
            fill = 'white', size = 0.25) +
  annotate('text', x = 87, y = 85, label = 'Already Linked', size = 2) +
  annotate('text', x = 87, y = 82, label = '        Deceased', size = 2) +
  annotate('text', x = 87, y = 79, label = '    Incarcerated', size = 2) +
  annotate('text', x = 87, y = 76, label = '          Declined', size = 2) +
  annotate('text', x = 87, y = 73, label = 'Ongoing linkage ', size = 2) +
  geom_rect(xmin = 41, xmax = 63, ymin = 75, ymax = 85, color = NA,
            fill = NA, size = 0.25) +
  annotate('text', x = 94, y = 85, label = mh_already_linked, size = 2, color = 'purple4') +
  annotate('text', x = 98, y = 85, label = mh_already_linked_percent, size = 2, color = 'magenta4') +
  annotate('text', x = 94, y = 82, label = mh_deceased, size = 2, color = 'purple4') +
  annotate('text', x = 98, y = 82, label = mh_deceased_percent, size = 2, color = 'magenta4') +
  annotate('text', x = 94, y = 79, label = mh_incarcerated, size = 2, color = 'purple4') +
  annotate('text', x = 98, y = 79, label = mh_incarcerated_percent, size = 2, color = 'magenta4') +
  annotate('text', x = 94, y = 76, label = mh_linkage_declined, size = 2, color = 'purple4') +
  annotate('text', x = 98, y = 76, label = mh_linkage_declined_percent, size = 2, color = 'magenta4') +
  annotate('text', x = 94, y = 73, label = mh_ongoing_linkage, size = 2, color = 'purple4') +
  annotate('text', x = 98, y = 73, label = mh_ongoing_linkage_percent, size = 2, color = 'magenta4') +
  
  
  # Eligible for Linkage
  geom_rect(xmin = 0, xmax = 22, ymin = 60, ymax = 70, color = 'black',
            fill = 'mediumpurple1', size = 0.25, size = 0.25) +
  annotate('text', x = 10.5, y = 67, label = 'Eligible for Linkage', size = 2) +
  geom_rect(xmin = 0, xmax = 22, ymin = 60, ymax = 70, color = NA,
            fill = NA, size = 0.25) +
  annotate('text', x = 10.5, y = 63, label = mh_eligible_ltc, size = 2, color = 'purple4') +
  annotate('text', x = 19, y = 63, label = mh_eligible_ltc_percent, size = 2, color = 'magenta4') +
  
  
  # In Progress
  geom_rect(xmin = 41, xmax = 63, ymin = 45, ymax = 55, color = 'gray',
            fill = 'white', size = 0.25) +
  annotate('text', x = 50.5, y = 52, label = 'In Progress', size = 2) +
  geom_rect(xmin = 41, xmax = 63, ymin = 45, ymax = 55, color = NA,
            fill = NA, size = 0.25) +
  annotate('text', x = 51.5, y = 48, label = mh_in_progress, size = 2, color = 'purple4') +
  annotate('text', x = 60, y = 48, label = mh_in_progress_percent, size = 2, color = 'magenta4') +
  
  
  # In Progress over 90 days
  geom_rect(xmin = 41, xmax = 63, ymin = 37, ymax = 44, color = NA,
            fill = 'white', size = 0.25, size = 0.25) +
  annotate('text', x = 52, y = 42, label = '>90 days:', size = 2) +
  geom_rect(xmin = 41, xmax = 63, ymin = 37, ymax = 44, color = NA,
            fill = NA, size = 0.25) +
  annotate('text', x = 56, y = 42, label = mh_in_progress_90days, size = 2, color = 'purple4') +
  annotate('text', x = 60, y = 42, label = mh_in_progress_90days_percent, size = 2, color = 'magenta4') +
  
  
  # Closed Cases
  geom_rect(xmin = 0, xmax = 22, ymin = 30, ymax = 40, color = 'black',
            fill = 'mediumpurple1', size = 0.25, size = 0.25) +
  annotate('text', x = 10.5, y = 37, label = 'Closed Cases', size = 2) +
  geom_rect(xmin = 0, xmax = 22, ymin = 30, ymax = 40, color = NA,
            fill = NA, size = 0.25) +
  annotate('text', x = 10.5, y = 33, label = mh_closed_case, size = 2, color = 'purple4') +
  annotate('text', x = 19, y = 33, label = mh_closed_case_percent, size = 2, color = 'magenta4') +
  
  
  # Not Linked
  geom_rect(xmin = 41, xmax = 63, ymin = 15, ymax = 25, color = 'gray',
            fill = 'white', size = 0.25) +
  annotate('text', x = 50.5, y = 22, label = 'Not Linked', size = 2) +
  geom_rect(xmin = 41, xmax = 63, ymin = 15, ymax = 25, color = NA,
            fill = NA, size = 0.25) +
  annotate('text', x = 51.5, y = 18, label = mh_not_linked, size = 2, color = 'purple4') +
  annotate('text', x = 60, y = 18, label = mh_not_linked_percent, size = 2, color = 'magenta4') +
  
  
  # Reasons Not Linked
  geom_rect(xmin = 83, xmax = 100, ymin = 0, ymax = 30, color = NA,
            fill = 'white', size = 0.25) +
  annotate('text', x = 87, y = 26, label = 'Med Staff interferes    ', size = 2) +
  annotate('text', x = 87, y = 23, label = '  Family interferes', size = 2) +
  annotate('text', x = 87, y = 20, label = '    Refuses to talk', size = 2) +
  annotate('text', x = 87, y = 17, label = '    Personal safety', size = 2) +
  annotate('text', x = 87, y = 14, label = '    Medical course', size = 2) +
  annotate('text', x = 87, y = 11, label = 'Inability to contact', size = 2) +
  annotate('text', x = 87, y = 8, label = ' Language barrier', size = 2) +
  annotate('text', x = 87, y = 5, label = '                   Other', size = 2) +
  geom_rect(xmin = 41, xmax = 63, ymin = 0, ymax = 30, color = NA,
            fill = NA, size = 0.25) +
  annotate('text', x = 94, y = 26, label = mh_not_linked_med_staff, size = 2, color = 'purple4') +
  annotate('text', x = 98, y = 26, label = mh_not_linked_med_staff_percent, size = 2, color = 'magenta4') +
  annotate('text', x = 94, y = 23, label = mh_not_linked_family, size = 2, color = 'purple4') +
  annotate('text', x = 98, y = 23, label = mh_not_linked_family_percent, size = 2, color = 'magenta4') +
  annotate('text', x = 94, y = 20, label = mh_not_linked_not_talking, size = 2, color = 'purple4') +
  annotate('text', x = 98, y = 20, label = mh_not_linked_not_talking_percent, size = 2, color = 'magenta4') +
  annotate('text', x = 94, y = 17, label = mh_not_linked_safety, size = 2, color = 'purple4') +
  annotate('text', x = 98, y = 17, label = mh_not_linked_safety_percent, size = 2, color = 'magenta4') +
  annotate('text', x = 94, y = 14, label = mh_not_linked_medical, size = 2, color = 'purple4') +
  annotate('text', x = 98, y = 14, label = mh_not_linked_medical_percent, size = 2, color = 'magenta4') +
  annotate('text', x = 94, y = 11, label = mh_not_linked_contact, size = 2, color = 'purple4') +
  annotate('text', x = 98, y = 11, label = mh_not_linked_contact_percent, size = 2, color = 'magenta4') +
  annotate('text', x = 94, y = 8, label = mh_not_linked_language, size = 2, color = 'purple4') +
  annotate('text', x = 98, y = 8, label = mh_not_linked_language_percent, size = 2, color = 'magenta4') +
  annotate('text', x = 94, y = 5, label = mh_not_linked_other, size = 2, color = 'purple4') +
  annotate('text', x = 98, y = 5, label = mh_not_linked_other_percent, size = 2, color = 'magenta4') +
  
  
  # Linked to Care
  geom_rect(xmin = 0, xmax = 22, ymin = 0, ymax = 10, color = 'black',
            fill = 'mediumpurple1', size = 0.25, size = 0.25) +
  annotate('text', x = 10.5, y = 7, label = 'Linked to Care', size = 2) +
  geom_rect(xmin = 0, xmax = 22, ymin = 0, ymax = 10, color = NA,
            fill = NA, size = 0.25) +
  annotate('text', x = 10.5, y = 3, label = mh_linked, size = 2, color = 'purple4') +
  annotate('text', x = 19, y = 3, label = mh_linked_percent, size = 2, color = 'magenta4') +
  
  
  # Down Arrow 1
  geom_segment(
    x = 10.5, xend = 10.5, y = 90, yend = 70, 
    size = 0.15, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(2,"mm"), type = "closed")) +
  
  # Down Arrow 2
  geom_segment(
    x = 10.5, xend = 10.5, y = 60, yend = 40, 
    size = 0.15, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(2,"mm"), type = "closed")) +
  
  # Down Arrow 3
  geom_segment(
    x = 10.5, xend = 10.5, y = 30, yend = 10, 
    size = 0.15, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(2,"mm"), type = "closed")) +
  
  # Rigmh Arrow 1
  geom_segment(
    x = 10.5, xend = 41, y = 80, yend = 80, 
    size = 0.05, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1,"mm"), type = "closed"), color = 'darkgray') +
  
  # Rigmh Arrow 2
  geom_segment(
    x = 10.5, xend = 41, y = 50, yend = 50, 
    size = 0.05, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1,"mm"), type = "closed"), color = 'darkgray') +
  
  # Rigmh Arrow 3
  geom_segment(
    x = 10.5, xend = 41, y = 20, yend = 20, 
    size = 0.05, linejoin = "mitre", lineend = "butt",
    arrow = arrow(length = unit(1,"mm"), type = "closed"), color = 'darkgray') +
  
  # Rigmh Line 1
  geom_segment(
    x = 63, xend = 81, y = 80, yend = 80, 
    size = 0.15, linejoin = "mitre", lineend = "butt", linetype = "dotted") +
  
  # Rigmh Line 2
  geom_segment(
    x = 63, xend = 80, y = 20, yend = 20, 
    size = 0.15, linejoin = "mitre", lineend = "butt", linetype = "dotted")->
  grid

grid + theme_void()

```



