---
title: "UC Medical Center (UCMC)"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r 2023 Data, include=FALSE}

library(dplyr)
library(tidyverse)
library(lubridate)
library(plotly)
library(ggplot2)
library(reactable)
library(htmltools)
library(lubridate)
library(hrbrthemes)
library(gt)
library(janitor)
library(scales)
library(apyramid)
library(kableExtra)

patients23_1 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230103.csv')
patients23_2 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230110.csv')
patients23_3 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230117.csv')
patients23_4 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230124.csv')
patients23_5 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230131.csv')
patients23_6 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230203.csv')
patients23_7 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230207.csv')
patients23_8 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230221.csv')
patients23_9 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230301.csv')
patients23_10 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230307.csv')
patients23_11 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230314.csv')
patients23_12 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230321.csv')
patients23_13 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230328.csv')
patients23_14 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230403.csv')
patients23_15 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230411.csv')
patients23_16 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230418.csv')
patients23_17 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230425.csv')
patients23_18 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230502.csv')
patients23_19 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230509.csv')
patients23_20 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230516.csv')
patients23_21 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230523.csv')
patients23_22 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230601.csv')
patients23_23 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230606.csv')
patients23_24 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230613.csv')
patients23_25 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230620.csv')
patients23_26 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230627.csv')
patients23_27 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230706.csv')
patients23_28 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230711.csv')
patients23_29 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230718.csv')
patients23_30 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230725.csv')
patients23_31 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230801.csv')
patients23_32 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230808.csv')
patients23_33 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230815.csv')
patients23_34 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230822.csv')
patients23_35 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230829.csv')
patients23_36 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230905.csv')
patients23_37 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230912.csv')
patients23_38 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230919.csv')
patients23_39 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20230926.csv')
patients23_40 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20231003.csv')
patients23_41 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20231010.csv')
patients23_42 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20231017.csv')
patients23_43 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20231024.csv')
patients23_44 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20231101.csv')
patients23_45 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20231107.csv')
patients23_46 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20231114.csv')
patients23_47 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20231121.csv')
patients23_48 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20231128.csv')
patients23_49 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20231205.csv')
patients23_50 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20231212.csv')
patients23_51 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20231219.csv')
patients23_52 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20231226.csv')
patients23_53 <- read.csv('M:/EIP Data/External Data Sources/CHI Data/2023/DPI_1009_ed_patient_list_20240102.csv')



patients23 <- rbind(patients23_1, patients23_2, patients23_3, patients23_4, patients23_5, patients23_6, patients23_7, patients23_8, patients23_9, patients23_10,
                  patients23_11, patients23_12, patients23_13, patients23_14, patients23_15, patients23_16, patients23_17, patients23_18, patients23_19, patients23_20,
                  patients23_21, patients23_22, patients23_23, patients23_24, patients23_25, patients23_26, patients23_27, patients23_28, patients23_29, patients23_30,
                  patients23_31, patients23_32, patients23_33, patients23_34, patients23_35, patients23_36, patients23_37, patients23_38, patients23_39, patients23_40,
                  patients23_41, patients23_42, patients23_43, patients23_44, patients23_45, patients23_46, patients23_47, patients23_48, patients23_49, patients23_50, patients23_51, patients23_52, patients23_53)
dim(patients23)
head(patients23)

summary(patients23$EVENT_TIME)
patients23$date <- as.Date(patients23$EVENT_TIME, format = '%m/%d/%Y')
summary(patients23$date)
patients23 <- patients23[which(patients23$date >= '2023-01-01' & patients23$date <= '2023-12-31'), ]
summary(patients23$date)
dim(patients23)

table(patients23$DEPARTMENT)
patients23 <- patients23[which(patients23$DEPARTMENT == 'UH EMERGENCY DEPT'), ]
table(patients23$DEPARTMENT)
dim(patients23)

patients23 <- select(patients23, PAT_ENC_CSN_ID, date, MRN, PATIENT_LAST_NAME, PATIENT_FIRST_NAME,
                     PATIENT_MIDDLE_NAME, DOB, AGE, RACE, GENDER)
colnames(patients23)[1] <- 'csn'
colnames(patients23)[3] <- 'mrn'
colnames(patients23)[4] <- 'last_name'
colnames(patients23)[5] <- 'first_name'
colnames(patients23)[6] <- 'middle_name'
colnames(patients23)[7] <- 'dob'
colnames(patients23)[8] <- 'age'
colnames(patients23)[9] <- 'race'
colnames(patients23)[10] <- 'gender'
head(patients23)


# Number of Encounters at UCMC
ucmc_encounters23 <- select(patients23, csn)
dim(ucmc_encounters23)
head(ucmc_encounters23)
ucmc_encounters23 <- distinct(ucmc_encounters23)
dim(ucmc_encounters23)
ucmc_encounters23 <- nrow(ucmc_encounters23)
ucmc_encounters23


ucmc_monthly_enc23_1 <- patients23[which(patients23$date >= '2023-01-01' & patients23$date <= '2023-01-31'), ]
ucmc_monthly_enc23_1 <- select(ucmc_monthly_enc23_1, csn)
dim(ucmc_monthly_enc23_1)
ucmc_monthly_enc23_1 <- distinct(ucmc_monthly_enc23_1)
dim(ucmc_monthly_enc23_1)
ucmc_enc23_1 <- nrow(ucmc_monthly_enc23_1)

ucmc_monthly_enc23_2 <- patients23[which(patients23$date >= '2023-02-01' & patients23$date <= '2023-02-28'), ]
ucmc_monthly_enc23_2 <- select(ucmc_monthly_enc23_2, csn)
dim(ucmc_monthly_enc23_2)
ucmc_monthly_enc23_2 <- distinct(ucmc_monthly_enc23_2)
dim(ucmc_monthly_enc23_2)
ucmc_enc23_2 <- nrow(ucmc_monthly_enc23_2)

ucmc_monthly_enc23_3 <- patients23[which(patients23$date >= '2023-03-01' & patients23$date <= '2023-03-31'), ]
ucmc_monthly_enc23_3 <- select(ucmc_monthly_enc23_3, csn)
dim(ucmc_monthly_enc23_3)
ucmc_monthly_enc23_3 <- distinct(ucmc_monthly_enc23_3)
dim(ucmc_monthly_enc23_3)
ucmc_enc23_3 <- nrow(ucmc_monthly_enc23_3)

ucmc_monthly_enc23_4 <- patients23[which(patients23$date >= '2023-04-01' & patients23$date <= '2023-04-30'), ]
ucmc_monthly_enc23_4 <- select(ucmc_monthly_enc23_4, csn)
dim(ucmc_monthly_enc23_4)
ucmc_monthly_enc23_4 <- distinct(ucmc_monthly_enc23_4)
dim(ucmc_monthly_enc23_4)
ucmc_enc23_4 <- nrow(ucmc_monthly_enc23_4)

ucmc_monthly_enc23_5 <- patients23[which(patients23$date >= '2023-05-01' & patients23$date <= '2023-05-31'), ]
ucmc_monthly_enc23_5 <- select(ucmc_monthly_enc23_5, csn)
dim(ucmc_monthly_enc23_5)
ucmc_monthly_enc23_5 <- distinct(ucmc_monthly_enc23_5)
dim(ucmc_monthly_enc23_5)
ucmc_enc23_5 <- nrow(ucmc_monthly_enc23_5)

ucmc_monthly_enc23_6 <- patients23[which(patients23$date >= '2023-06-01' & patients23$date <= '2023-06-30'), ]
ucmc_monthly_enc23_6 <- select(ucmc_monthly_enc23_6, csn)
dim(ucmc_monthly_enc23_6)
ucmc_monthly_enc23_6 <- distinct(ucmc_monthly_enc23_6)
dim(ucmc_monthly_enc23_6)
ucmc_enc23_6 <- nrow(ucmc_monthly_enc23_6)

ucmc_monthly_enc23_7 <- patients23[which(patients23$date >= '2023-07-01' & patients23$date <= '2023-07-31'), ]
ucmc_monthly_enc23_7 <- select(ucmc_monthly_enc23_7, csn)
dim(ucmc_monthly_enc23_7)
ucmc_monthly_enc23_7 <- distinct(ucmc_monthly_enc23_7)
dim(ucmc_monthly_enc23_7)
ucmc_enc23_7 <- nrow(ucmc_monthly_enc23_7)

ucmc_monthly_enc23_8 <- patients23[which(patients23$date >= '2023-08-01' & patients23$date <= '2023-08-31'), ]
ucmc_monthly_enc23_8 <- select(ucmc_monthly_enc23_8, csn)
dim(ucmc_monthly_enc23_8)
ucmc_monthly_enc23_8 <- distinct(ucmc_monthly_enc23_8)
dim(ucmc_monthly_enc23_8)
ucmc_enc23_8 <- nrow(ucmc_monthly_enc23_8)

ucmc_monthly_enc23_9 <- patients23[which(patients23$date >= '2023-09-01' & patients23$date <= '2023-09-30'), ]
ucmc_monthly_enc23_9 <- select(ucmc_monthly_enc23_9, csn)
dim(ucmc_monthly_enc23_9)
ucmc_monthly_enc23_9 <- distinct(ucmc_monthly_enc23_9)
dim(ucmc_monthly_enc23_9)
ucmc_enc23_9 <- nrow(ucmc_monthly_enc23_9)

ucmc_monthly_enc23_10 <- patients23[which(patients23$date >= '2023-10-01' & patients23$date <= '2023-10-31'), ]
ucmc_monthly_enc23_10 <- select(ucmc_monthly_enc23_10, csn)
dim(ucmc_monthly_enc23_10)
ucmc_monthly_enc23_10 <- distinct(ucmc_monthly_enc23_10)
dim(ucmc_monthly_enc23_10)
ucmc_enc23_10 <- nrow(ucmc_monthly_enc23_10)

ucmc_monthly_enc23_11 <- patients23[which(patients23$date >= '2023-11-01' & patients23$date <= '2023-11-30'), ]
ucmc_monthly_enc23_11 <- select(ucmc_monthly_enc23_11, csn)
dim(ucmc_monthly_enc23_11)
ucmc_monthly_enc23_11 <- distinct(ucmc_monthly_enc23_11)
dim(ucmc_monthly_enc23_11)
ucmc_enc23_11 <- nrow(ucmc_monthly_enc23_11)

ucmc_monthly_enc23_12 <- patients23[which(patients23$date >= '2023-12-01' & patients23$date <= '2023-12-31'), ]
ucmc_monthly_enc23_12 <- select(ucmc_monthly_enc23_12, csn)
dim(ucmc_monthly_enc23_12)
ucmc_monthly_enc23_12 <- distinct(ucmc_monthly_enc23_12)
dim(ucmc_monthly_enc23_12)
ucmc_enc23_12 <- nrow(ucmc_monthly_enc23_12)


# Number of Patients at UCMC
ucmc_patients23 <- select(patients23, mrn)
dim(ucmc_patients23)
head(ucmc_patients23)
ucmc_patients23 <- distinct(ucmc_patients23)
dim(ucmc_patients23)
ucmc_patients23 <- nrow(ucmc_patients23)
ucmc_patients23


ucmc_monthly_pt23_1 <- patients23[which(patients23$date >= '2023-01-01' & patients23$date <= '2023-01-31'), ]
ucmc_monthly_pt23_1 <- select(ucmc_monthly_pt23_1, mrn)
dim(ucmc_monthly_pt23_1)
ucmc_monthly_pt23_1 <- distinct(ucmc_monthly_pt23_1)
dim(ucmc_monthly_pt23_1)
ucmc_pts23_1 <- nrow(ucmc_monthly_pt23_1)

ucmc_monthly_pt23_2 <- patients23[which(patients23$date >= '2023-02-01' & patients23$date <= '2023-02-28'), ]
ucmc_monthly_pt23_2 <- select(ucmc_monthly_pt23_2, mrn)
dim(ucmc_monthly_pt23_2)
ucmc_monthly_pt23_2 <- distinct(ucmc_monthly_pt23_2)
dim(ucmc_monthly_pt23_2)
ucmc_pts23_2 <- nrow(ucmc_monthly_pt23_2)

ucmc_monthly_pt23_3 <- patients23[which(patients23$date >= '2023-03-01' & patients23$date <= '2023-03-31'), ]
ucmc_monthly_pt23_3 <- select(ucmc_monthly_pt23_3, mrn)
dim(ucmc_monthly_pt23_3)
ucmc_monthly_pt23_3 <- distinct(ucmc_monthly_pt23_3)
dim(ucmc_monthly_pt23_3)
ucmc_pts23_3 <- nrow(ucmc_monthly_pt23_3)

ucmc_monthly_pt23_4 <- patients23[which(patients23$date >= '2023-04-01' & patients23$date <= '2023-04-30'), ]
ucmc_monthly_pt23_4 <- select(ucmc_monthly_pt23_4, mrn)
dim(ucmc_monthly_pt23_4)
ucmc_monthly_pt23_4 <- distinct(ucmc_monthly_pt23_4)
dim(ucmc_monthly_pt23_4)
ucmc_pts23_4 <- nrow(ucmc_monthly_pt23_4)

ucmc_monthly_pt23_5 <- patients23[which(patients23$date >= '2023-05-01' & patients23$date <= '2023-05-31'), ]
ucmc_monthly_pt23_5 <- select(ucmc_monthly_pt23_5, mrn)
dim(ucmc_monthly_pt23_5)
ucmc_monthly_pt23_5 <- distinct(ucmc_monthly_pt23_5)
dim(ucmc_monthly_pt23_5)
ucmc_pts23_5 <- nrow(ucmc_monthly_pt23_5)

ucmc_monthly_pt23_6 <- patients23[which(patients23$date >= '2023-06-01' & patients23$date <= '2023-06-30'), ]
ucmc_monthly_pt23_6 <- select(ucmc_monthly_pt23_6, mrn)
dim(ucmc_monthly_pt23_6)
ucmc_monthly_pt23_6 <- distinct(ucmc_monthly_pt23_6)
dim(ucmc_monthly_pt23_6)
ucmc_pts23_6 <- nrow(ucmc_monthly_pt23_6)

ucmc_monthly_pt23_7 <- patients23[which(patients23$date >= '2023-07-01' & patients23$date <= '2023-07-31'), ]
ucmc_monthly_pt23_7 <- select(ucmc_monthly_pt23_7, mrn)
dim(ucmc_monthly_pt23_7)
ucmc_monthly_pt23_7 <- distinct(ucmc_monthly_pt23_7)
dim(ucmc_monthly_pt23_7)
ucmc_pts23_7 <- nrow(ucmc_monthly_pt23_7)

ucmc_monthly_pt23_8 <- patients23[which(patients23$date >= '2023-08-01' & patients23$date <= '2023-08-31'), ]
ucmc_monthly_pt23_8 <- select(ucmc_monthly_pt23_8, mrn)
dim(ucmc_monthly_pt23_8)
ucmc_monthly_pt23_8 <- distinct(ucmc_monthly_pt23_8)
dim(ucmc_monthly_pt23_8)
ucmc_pts23_8 <- nrow(ucmc_monthly_pt23_8)

ucmc_monthly_pt23_9 <- patients23[which(patients23$date >= '2023-09-01' & patients23$date <= '2023-09-30'), ]
ucmc_monthly_pt23_9 <- select(ucmc_monthly_pt23_9, mrn)
dim(ucmc_monthly_pt23_9)
ucmc_monthly_pt23_9 <- distinct(ucmc_monthly_pt23_9)
dim(ucmc_monthly_pt23_9)
ucmc_pts23_9 <- nrow(ucmc_monthly_pt23_9)

ucmc_monthly_pt23_10 <- patients23[which(patients23$date >= '2023-10-01' & patients23$date <= '2023-10-31'), ]
ucmc_monthly_pt23_10 <- select(ucmc_monthly_pt23_10, mrn)
dim(ucmc_monthly_pt23_10)
ucmc_monthly_pt23_10 <- distinct(ucmc_monthly_pt23_10)
dim(ucmc_monthly_pt23_10)
ucmc_pts23_10 <- nrow(ucmc_monthly_pt23_10)

ucmc_monthly_pt23_11 <- patients23[which(patients23$date >= '2023-11-01' & patients23$date <= '2023-11-30'), ]
ucmc_monthly_pt23_11 <- select(ucmc_monthly_pt23_11, mrn)
dim(ucmc_monthly_pt23_11)
ucmc_monthly_pt23_11 <- distinct(ucmc_monthly_pt23_11)
dim(ucmc_monthly_pt23_11)
ucmc_pts23_11 <- nrow(ucmc_monthly_pt23_11)

ucmc_monthly_pt23_12 <- patients23[which(patients23$date >= '2023-12-01' & patients23$date <= '2023-12-31'), ]
ucmc_monthly_pt23_12 <- select(ucmc_monthly_pt23_12, mrn)
dim(ucmc_monthly_pt23_12)
ucmc_monthly_pt23_12 <- distinct(ucmc_monthly_pt23_12)
dim(ucmc_monthly_pt23_12)
ucmc_pts23_12 <- nrow(ucmc_monthly_pt23_12)

```


# Total Encounters & Unique Patients

The data table below is estimated encounter and patient data compiled using the weekly CHI files. The total number of encounters are determined by unique CSNs and the total number of unique patients are determined by unique MRNs.


```{r, echo=FALSE, warning=FALSE}

# Combining Encounter and Patient data into same table
ucmc_monthly_tbl <- data.frame(matrix(ncol = 3, nrow = 0))
colnames(ucmc_monthly_tbl) <- c('Month', 'Encounters/Visits', 'Unique Patients')
ucmc_monthly_tbl[nrow(ucmc_monthly_tbl) + 1,] <- list('January', ucmc_enc23_1, ucmc_pts23_1)
ucmc_monthly_tbl[nrow(ucmc_monthly_tbl) + 1,] <- list('February', ucmc_enc23_2, ucmc_pts23_2)
ucmc_monthly_tbl[nrow(ucmc_monthly_tbl) + 1,] <- list('March', ucmc_enc23_3, ucmc_pts23_3)
ucmc_monthly_tbl[nrow(ucmc_monthly_tbl) + 1,] <- list('April', ucmc_enc23_4, ucmc_pts23_4)
ucmc_monthly_tbl[nrow(ucmc_monthly_tbl) + 1,] <- list('May', ucmc_enc23_5, ucmc_pts23_5)
ucmc_monthly_tbl[nrow(ucmc_monthly_tbl) + 1,] <- list('June', ucmc_enc23_6, ucmc_pts23_6)
ucmc_monthly_tbl[nrow(ucmc_monthly_tbl) + 1,] <- list('July', ucmc_enc23_7, ucmc_pts23_7)
ucmc_monthly_tbl[nrow(ucmc_monthly_tbl) + 1,] <- list('August', ucmc_enc23_8, ucmc_pts23_8)
ucmc_monthly_tbl[nrow(ucmc_monthly_tbl) + 1,] <- list('September', ucmc_enc23_9, ucmc_pts23_9)
ucmc_monthly_tbl[nrow(ucmc_monthly_tbl) + 1,] <- list('October', ucmc_enc23_10, ucmc_pts23_10)
ucmc_monthly_tbl[nrow(ucmc_monthly_tbl) + 1,] <- list('November', ucmc_enc23_11, ucmc_pts23_11)
ucmc_monthly_tbl[nrow(ucmc_monthly_tbl) + 1,] <- list('December', ucmc_enc23_12, ucmc_pts23_12)
ucmc_monthly_tbl[nrow(ucmc_monthly_tbl) + 1,] <- list('2023 Totals', ucmc_encounters23, ucmc_patients23)
ucmc_monthly_tbl %>%
  kbl(table.attr = 'data-quarto-disable-processing="true"') %>%
  kable_paper(bootstrap_options = "striped", full_width = F) %>%
  pack_rows("2023", 1, 13, label_row_css = "background-color: #F0F0F0") %>%
  add_indent(c(1,2,3,4,5,6,7,8,9,10,11,12,13)) %>%
  kable_styling(full_width = F, font_size = 12)

```



